// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © amiryaffe

//@version=6
indicator(title="Buying The Dip for Day Trading", overlay = true)
import TradingView/ta/10


buying_the_dip_sign = "💰"
change_direction_sign = "👆"
dip_while_still_in_trend_sign = "📊"
relevant_timezone = "America/New_York"


////           Changing direction Indications           ////
current_bar_is_strong(index, low_src, high_src, close_src, open_src) =>
    has_high_lows = low_src[index] > low_src[index+1]
    has_high_highs = high_src[index] > high_src[index+1]
    is_solid_green = close_src[index] > open_src[index] and (high_src[index] - close_src[index]) / (close_src[index] - low_src[index]) < 0.3

    has_high_lows and has_high_highs and is_solid_green

current_bar_volume_is_strong(index) =>
    vol_avg = ta.sma(volume, 20)
    volume[index] > (volume[index+1] * 2) and volume[index] > vol_avg[index] and volume[index+1] <= vol_avg[index+1]

current_bar_is_near_to_9_ema(index, open_src, low_src, ema_9, ema_20, vwap) =>
    ema_9_is_higher = ema_9[index] > ema_20[index] and ema_9[index] > vwap[index]
    open_close_to_9_ema = math.abs(open_src[index] - ema_9[index]) < 0.05 and math.abs(low_src[index] - ema_9[index]) < 0.05

current_bar_is_bigger_than_last_one(index, close_src, open_src) =>
    (close_src[index] - open_src[index]) > math.abs(close_src[index+1] - open_src[index+1])

macd_is_positive(index, macdLine, histogram) =>
    current_macd_is_positive = macdLine[index] > 0
    current_histogram_stronger_than_before = histogram[index] > histogram[index+1]

////           Buying the Dip Indications           ////

current_bar_is_strong_green(index, bars_back) =>
    current_bars_is_positive = close[index] > open[index]
    current_bar_is_strong = (close[index] - open[index]) / (high[index] - open[index]) > 0.6
    current_volume_is_bigger_than_last_ones = true
    for i = 1 to bars_back
        if close[index+i] < open[index+i] and (volume[index+i] > volume[0] or volume[index+i]/volume[0] >= 0.8)
            current_volume_is_bigger_than_last_ones := false
            break

    current_bars_is_positive and current_bar_is_strong and current_volume_is_bigger_than_last_ones

volume_has_changed_significantly_in_the_last_bars(index, bars_back, multiply_by) =>
    vol_avg = ta.sma(volume, 20)
    volume_has_changed_significantly_in_the_last_bars = false
    volume_changed_index = 0

    for i = 1 to bars_back
        if volume[index+i] > volume[index+i+1] * multiply_by
            volume_has_changed_significantly_in_the_last_bars := true
            volume_changed_index := index+i
            break

    [volume_has_changed_significantly_in_the_last_bars, volume_changed_index]

macd_is_still_in_its_first_phase(index) =>
    [macdLine, signalLine, histogram] = ta.macd(close, 12, 26, 9)
    macd_is_still_in_its_first_phase = true
    for i = 0 to 5
        if signalLine[index+i] >= macdLine[index+i]
            macd_is_still_in_its_first_phase := false
            break
        if macdLine[index+i+1] > macdLine[index]
            macd_is_still_in_its_first_phase := false
            break

    macd_is_still_in_its_first_phase

current_bar_is_stronger_than_the_last_red_bars(index, bars_back) =>
    current_bar_is_stronger_than_the_last_red_bars = true

    for i = 1 to bars_back
        if close[index+i] > open[index+i]
            continue
        if volume[index+i] >= volume[index]
            current_bar_is_stronger_than_the_last_red_bars := false
            break

    current_bar_is_stronger_than_the_last_red_bars

current_bar_crossed_vwap_towards_up(index) =>
    vwap = ta.vwap(hlc3)
    open[index] < vwap[index] and close[index] > vwap[index]

current_bar_is_the_nearest_bar_to_9_ema(index) =>
    ema_9 = ta.ema(close, 9)

    last_bars_higher_than_9_ema = true
    for i = 0 to 3
        if low[index+i] < ema_9[index+i]
            last_bars_higher_than_9_ema := false
            break

    current_bar_is_the_nearest_bar_to_9_ema = true
    for i = 0 to 3
        if ema_9[index+i+1] >= ema_9[index+i]
            current_bar_is_the_nearest_bar_to_9_ema := false
            break

        if close[index+i+1] > open[index+i+1] and current_bar_crossed_vwap_towards_up(index+i+1)
            continue

        if (low[index+i+1] - ema_9[index+i+1]) < (low[index+i] - ema_9[index+i])
            current_bar_is_the_nearest_bar_to_9_ema := false
            break

    last_bars_higher_than_9_ema and current_bar_is_the_nearest_bar_to_9_ema

last_bars_showing_weak_downtrend(index) =>
    ema_9 = ta.ema(close, 9)
    last_bars_showing_weak_downtrend = false

    for i = 1 to 2
        has_low_of_lows = low[index+i+1] > low[index+1]
        has_low_highs = high[index+i+1] > high[index+1]
        volume_getting_slower = volume[index+i+1] > volume[index+1]
        getting_close_to_9_ema = ema_9[index+i+1] < ema_9[index+1] and (low[index+i+1] - ema_9[index+i+1] > low[index+1] - ema_9[index+1])
        last_bars_showing_weak_downtrend := has_low_of_lows
          and has_low_highs
          and volume_getting_slower
          and getting_close_to_9_ema

        if last_bars_showing_weak_downtrend
            break

    last_bars_showing_weak_downtrend

no_weak_green_bar_before(index, bars_back) =>
    weak_green_bar_before = false
    for i = 1 to bars_back
        if close[i] > open[i] and ((close[i] - low[i]) / (high[i] - close[i]) < 0.4)
            weak_green_bar_before := true

    not weak_green_bar_before


////           Changing direction Indications           ////
direction_has_changed_just_before(index, index_to_start_from) =>
    [macdLine, _, histogram] = ta.macd(close, 12, 26, 9)
    has_lower_points_between_to_high_highs = false
    macd_is_positive = false
    histogram_is_positive = false

    for i = 1 to index_to_start_from
        if index+i-1 < 0
            continue
        has_lower_points_between_to_high_highs := high[index+i] < high[index+i-1] and high[index+i] < high[index+i+1]
        histogram_is_positive := histogram[index+i+1] > 0 and histogram[index+i] > 0 and histogram[index+i-1] > 0
        macd_is_positive := macdLine[index+i+1] > 0 and macdLine[index+i] > 0 and macdLine[index+i-1] > 0
        if has_lower_points_between_to_high_highs and histogram_is_positive and macd_is_positive
            break

    has_lower_points_between_to_high_highs

last_bars_are_above_all_indicators(index) =>
    [_, _, histogram] = ta.macd(close, 12, 26, 9)
    last_bars_are_above_all_indicators = false
    ema_9 = ta.ema(close, 9)
    ema_20 = ta.ema(close, 20)
    vwap = ta.vwap(hlc3)
    vol_avg = ta.sma(volume, 20)

    for i = 0 to 2
        histogram_keeps_up = histogram[index+i] > histogram[index+i+1]
        low_above_vwap = low[index+i] > vwap[index+i]
        low_above_emas = low[index+i] > ema_9[index+i] and ema_9[index+i] > ema_20[index+i]
        volume_above_avg = volume[index+i] > vol_avg[index+i]
        last_bars_are_above_all_indicators := low_above_emas and low_above_vwap and volume_above_avg and histogram_keeps_up
        if not last_bars_are_above_all_indicators
            break

    current_volume_is_higher_than_last_ones = volume[index] > volume[index+1] and close[index] > close[index+1] and low[index] - 0.2 < ema_9[index]
    last_bars_are_above_all_indicators and current_volume_is_higher_than_last_ones

last_bars_volume_need_to_be_above_threshold(index, index_to_start_from) =>
    last_bars_volume_above_threshold = true
    min_volume_per_bar = 20000
    for i = index_to_start_from to index
        if volume[i] < min_volume_per_bar
            last_bars_volume_above_threshold := false
            break

    last_bars_volume_above_threshold

current_bar_is_dip_while_still_in_trend(index) =>
    [macdLine, _, histogram] = ta.macd(close, 12, 26, 9)
    current_bar_is_strong = current_bar_is_strong(index, low, high, close, open)
    current_bar_is_bigger_than_last_one = current_bar_is_bigger_than_last_one(index, close, open)
    macd_is_positive = macd_is_positive(index, macdLine, histogram)
    [volume_has_changed_significantly_in_the_last_bars, volume_changed_index] = volume_has_changed_significantly_in_the_last_bars(index, 5, 5)
    direction_has_changed_just_before = direction_has_changed_just_before(index, volume_changed_index)
    last_bars_are_above_all_indicators = last_bars_are_above_all_indicators(index)
    last_bars_volume_need_to_be_above_threshold = last_bars_volume_need_to_be_above_threshold(index, volume_changed_index)

    current_bar_is_dip_while_still_in_trend = current_bar_is_strong
     and current_bar_is_bigger_than_last_one
     and macd_is_positive
     and volume_has_changed_significantly_in_the_last_bars
     and direction_has_changed_just_before
     and last_bars_are_above_all_indicators
     and last_bars_volume_need_to_be_above_threshold
     and low[index] > 1

    if current_bar_is_dip_while_still_in_trend and year >= 2024
        log.info("volume_changed_index: {0}. timeframe: {1}", volume_changed_index, str.tonumber(timeframe.period))
    current_bar_is_dip_while_still_in_trend

///////// run indicators /////////

change_direction_indicator() =>
    index = 0
    vol_avg = ta.sma(volume, 20)
    ema_9 = ta.ema(close, 9)
    ema_20 = ta.ema(close, 20)
    vwap = ta.vwap(hlc3)
    [macdLine, _, histogram] = ta.macd(close, 12, 26, 9)

    current_bar_is_strong = current_bar_is_strong(index, low, high, close, open)
    current_bar_volume_is_strong = current_bar_volume_is_strong(index)
    current_bar_is_near_to_9_ema = current_bar_is_near_to_9_ema(index, open, low, ema_9, ema_20, vwap)
    current_bar_is_bigger_than_last_one = current_bar_is_bigger_than_last_one(index, close, open)
    macd_is_positive = macd_is_positive(index, macdLine, histogram)

    current_bar_is_potential = current_bar_is_strong
     and current_bar_volume_is_strong
     and current_bar_is_near_to_9_ema
     and current_bar_is_bigger_than_last_one
     and macd_is_positive

    already_happend_before = false
    failed_under_9_ema_in_between = false
    if current_bar_is_potential
        for i = 1 to 20
            if close[index+i] < ema_9[index+i] and open[index+i] < ema_9[index+i]
                failed_under_9_ema_in_between := true
                break

            // start current_bar_is_strong
            has_high_lows = low[index+i] > low[index+i+1]
            has_high_highs = high[index+i] > high[index+i+1]
            is_solid_green = close[index+i] > open[index+i] and (high[index+i] - close[index+i]) / (close[index+i] - low[index+i]) < 0.3
            current_bar_is_strong := has_high_lows and has_high_highs and is_solid_green
            // end current_bar_is_strong


            // start current_bar_volume_is_strong
            // if index == 11 and time == timestamp(relevant_timezone, year, month, 9, 9, 10) and timeframe.period == "5"
            //     log.info("c_v: {0}. p_v: {1}. c_v_a: {2}. p_v_a: {3}", volume[index], volume[index+1], vol_avg[index], vol_avg[index+1])
            current_bar_volume_is_strong := volume[index+i] > (volume[index+i+1] * 2) and volume[index+i] > vol_avg[index+i] and volume[index+i+1] <= vol_avg[index+i+1]
            // end current_bar_volume_is_strong

            // start current_bar_is_near_to_9_ema
            ema_9_is_higher = ema_9[index+i] > ema_20[index+i] and ema_9[index+i] > vwap[index+i]
            open_close_to_9_ema = math.abs(open[index+i] - ema_9[index+i]) < 0.05 and math.abs(low[index+i] - ema_9[index+i]) < 0.05
            current_bar_is_near_to_9_ema := ema_9_is_higher and open_close_to_9_ema
            // end current_bar_is_near_to_9_ema

            // start current_bar_is_bigger_than_last_one
            current_bar_is_bigger_than_last_one := (close[index+i] - open[index+i]) > math.abs(close[index+i+1] - open[index+i+1])
            // end current_bar_is_bigger_than_last_one

            // start macd_is_positive
            current_macd_is_positive = macdLine[index+i] > 0
            current_histogram_stronger_than_before = histogram[index+i] > histogram[index+i+1]
            macd_is_positive := current_macd_is_positive and current_histogram_stronger_than_before

            already_happend_before := current_bar_is_strong
             and current_bar_volume_is_strong
             and current_bar_is_near_to_9_ema
             and current_bar_is_bigger_than_last_one
             and macd_is_positive

            if already_happend_before
                // log.info("i: {0}", index+i)
                break

    already_happend_before and not failed_under_9_ema_in_between

buying_the_dip_run_indicator() =>
    index = 0
    bars_back = 10

    current_bar_is_strong_green = current_bar_is_strong_green(index, bars_back)
    [volume_has_changed_significantly_in_the_last_bars, volume_changed_index] = volume_has_changed_significantly_in_the_last_bars(index, bars_back, 10)
    macd_is_still_in_its_first_phase = macd_is_still_in_its_first_phase(index)
    current_bar_is_stronger_than_the_last_red_bars = current_bar_is_stronger_than_the_last_red_bars(index, bars_back)
    current_bar_is_the_nearest_bar_to_9_ema = current_bar_is_the_nearest_bar_to_9_ema(index)
    current_bar_crossed_vwap_towards_up = current_bar_crossed_vwap_towards_up(index)
    last_bars_showing_weak_downtrend = last_bars_showing_weak_downtrend(index)
    no_weak_green_bar_before = no_weak_green_bar_before(index, bars_back)

    current_bar_is_strong_green
      and volume_has_changed_significantly_in_the_last_bars
      and macd_is_still_in_its_first_phase
      and current_bar_is_stronger_than_the_last_red_bars
      and current_bar_is_the_nearest_bar_to_9_ema
      and current_bar_crossed_vwap_towards_up
      and last_bars_showing_weak_downtrend
      and no_weak_green_bar_before

buying_the_dip_indication = buying_the_dip_run_indicator()
change_direction_indication = str.tonumber(timeframe.period) >= 5 ? change_direction_indicator() : false
current_bar_is_dip_while_still_in_trend = current_bar_is_dip_while_still_in_trend(0)

plotshape(buying_the_dip_indication, title="Buying the dip indication", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = buying_the_dip_sign)
plotshape(change_direction_indication, title="Change direction indication", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = change_direction_sign)
plotshape(current_bar_is_dip_while_still_in_trend, title="Dip while still in trend", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.belowbar, text = dip_while_still_in_trend_sign)


alertcondition(buying_the_dip_indication or change_direction_indication or current_bar_is_dip_while_still_in_trend, title="Buying the dip indication", message="Buying the dip indication")
