// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TheFirstPatienceTrader

indicator(title="Change Upwards", overlay = true, max_bars_back = 5000)
import TradingView/ta/10

//@version=6

relevant_timezone = "America/New_York"

ema_9 = ta.ema(close, 9)
ema_20 = ta.ema(close, 20)
vwap = ta.vwap(hlc3)
vol_avg = ta.sma(volume, 20)
[macd, signal_line, histogram] = ta.macd(close, 12, 26, 9)
current_timeframe = str.tonumber(timeframe.period)
if timeframe.period == "10S"
    current_timeframe := 10

_made_more_than_usual_percentage_already(index, percentage) =>
    yesterday_close = request.security(syminfo.tickerid, "D", close[1], lookahead = barmerge.lookahead_on)
    if (hour[index] == 9 and minute[index] < 30) or hour[index] < 9
        yesterday_close := request.security(syminfo.tickerid, "D", close, lookahead = barmerge.lookahead_on)
    (close[index] - yesterday_close)/open[index] > percentage

change_upwards_indication(index) =>
    percentage = 0.1
    made_more_than_usual_percentage_already = _made_more_than_usual_percentage_already(index, percentage)
    bar_is_above_all_indicators = close[index] > ema_9[index]-0.01
     and close[index] > vwap[index]-0.01

    minutes_back_to_market_start = ((hour[index] - 4) * 60) + minute[index]

    bars_back = int(minutes_back_to_market_start/current_timeframe)

    start_index = 0
    for i = bars_back to index+1
        if i < 0
            continue
        volume_starts_to_move = volume[i] > volume[i+1] * 4
        price_starts_to_move = (high[i] - low[i]) > (high[i+1] - low[i+1]) * 2
        histogram_became_positive = histogram[i] > 0
         and (histogram[i+1] < 0
              or histogram[i] > histogram[i+1] * 5
              or (histogram[i+1] < histogram[i+2] and histogram[i+1] < histogram[i]))

        bar_is_positive = close[i] > open[i]
        volume_avg_has_changed = vol_avg[i] > vol_avg[i+1] * 2

        if true
         and volume_starts_to_move
         and price_starts_to_move
         and bar_is_positive
         and histogram_became_positive
         and volume_avg_has_changed
            start_index := i
            break

    if start_index == 0
        for i = index+1 to bars_back
            if i < 0
                continue
            volume_starts_to_move = volume[i] > volume[i+1] * 3
            price_starts_to_move = (high[i] - low[i]) > (high[i+1] - low[i+1]) * 2
            histogram_became_positive = histogram[i] > 0
            bar_is_positive = close[i] > open[i]
            crossed_vwap = open[i] < vwap[i]
             and close[i] > vwap[i]

            if true
             and volume_starts_to_move
             and price_starts_to_move
             and bar_is_positive
             and histogram_became_positive
                start_index := i
                break

    lower_histogram_start_index = 0
    for j = index+1 to start_index
        if j-1 < 0
            continue
        if histogram[j] > histogram[j+1]
         and histogram[j] > histogram[j-1]
            lower_histogram_start_index := j-1
            break

    no_too_much_lower_histogram = true
    no_lower_bar_is_higher_or_stronger_than_start = true
    for j = lower_histogram_start_index to index+1
        if histogram[j]/histogram[lower_histogram_start_index+1] < 0.5
            no_too_much_lower_histogram := false
        if high[j] > high[lower_histogram_start_index+1]
         and close[j] > open[j]
            no_lower_bar_is_higher_or_stronger_than_start := false

    upper_histogram_bars_counter = 0
    for j = lower_histogram_start_index+1 to start_index
        if histogram[j] < histogram[j+1]
            break
        upper_histogram_bars_counter += 1

    trend_is_strong = upper_histogram_bars_counter/lower_histogram_start_index >= 0.5

    no_bar_before_has_strong_volume = true
    for j = lower_histogram_start_index to index+1
        if j - index <= 1
            break
        if volume[j] > volume[index]
         and close[j] < open[j]
         and high[j] > high[index]
            no_bar_before_has_strong_volume := false
            break

    if no_bar_before_has_strong_volume
        for j = lower_histogram_start_index to index
            is_strong_negative_bar = volume[j] > vol_avg[j] * 3
             and close[j] < open[j]

            is_strong_positive_bar_but_weaker = is_strong_negative_bar
             and volume[j+1]/volume[j] > 0.5
             and volume[j+1] > 1000000
             and volume[j+1] < volume[j]
             and close[j+1] > open[j+1]

            if is_strong_positive_bar_but_weaker
                // if time == timestamp(relevant_timezone, year, 4, 4, 11, 30) and current_timeframe == 15
                //     log.info("j: {0}, lower_histogram_start_index: {1}", j, lower_histogram_start_index)
                no_bar_before_has_strong_volume := false
                break

    histogram_before_is_positive_but_weaker = true
     and histogram[index+1] > 0
     and macd[index+1] > 0
     and signal_line[index+1] > 0
     and histogram[index] > histogram[index+1]
     and histogram[index+2] > histogram[index+1]

    if current_timeframe < 15
        previous_bar_is_much_weaker = math.abs(close[index+1] - open[index+1])/(close[index] - open[index]) < 0.5
         and volume[index] > volume[index+1] * 2
        histogram_before_is_positive_but_weaker := histogram_before_is_positive_but_weaker
         and (histogram[index+2] < histogram[index+3] or previous_bar_is_much_weaker)

    histogram_was_positive_until_now = true
    if hour[start_index] > 9 or hour[start_index] == 9 and minute[start_index] > 30
        for i = start_index to index
            if histogram[i] < 0
                histogram_was_positive_until_now := false
                break

    highest_histogram = 0.0
    for i = start_index to index
        if histogram[i] > highest_histogram
            highest_histogram := histogram[i]

    current_histogram_is_high_enough = histogram[index]/highest_histogram >= 0.4

    volume_is_stronger_than_before = true
     and volume[index] > 100000
     and volume[index+1] > 100000
     and volume[index] > vol_avg[index]

    most_of_move_already_happend = false
    for i = index to start_index
        if i-1 < 0
            continue
        momentum_change_downwards = histogram[i] > histogram[i+1]
         and histogram[i] > histogram[i-1]

        if momentum_change_downwards
            distance_from_start = start_index - i
            if distance_from_start > (i-1) * 3 and not current_histogram_is_high_enough
                most_of_move_already_happend := true
                break

    only_on_higher_timeframes = current_timeframe >= 2

    overlapped_bars = 0
    for i = lower_histogram_start_index to index
        if i < 0
            continue
        if (high[i+1] - low[i])/(high[i] - low[i]) > 0.5
            overlapped_bars += 1
    most_bars_are_not_overlapped = overlapped_bars/lower_histogram_start_index < 0.5

    crossed_at_least_ones_under_9_ema = false
    if current_timeframe == 15
        crossed_at_least_ones_under_9_ema := true
    else
        for i = start_index-1 to index+1
            if i < 0
                continue

            if (low[i] < ema_9[i] or ema_9[i]/low[i] > 0.95)
             and close[i] > ema_9[i]
             and start_index - i > i - index
                // if time == timestamp(relevant_timezone, year, 5, 6, 9, 05) and current_timeframe == 5
                //     log.info("i: {0}, distance: {1}", i, ema_9[i]/low[i])
                crossed_at_least_ones_under_9_ema := true

    current_bar_body_is_solid = (close[index] - open[index])/(high[index] - low[index]) >= 0.5
     or (close[index] > close[index+1] and (close[index] - open[index])/(high[index] - open[index]) > 0.5)
    current_bar_volume_is_solid = volume[index] >= 500000

    result = true
     and made_more_than_usual_percentage_already
     and bar_is_above_all_indicators
     and histogram_before_is_positive_but_weaker
     and volume_is_stronger_than_before
     and only_on_higher_timeframes
     and histogram_was_positive_until_now
     and start_index != 0
     and not most_of_move_already_happend
     and current_histogram_is_high_enough
     and no_bar_before_has_strong_volume
     and trend_is_strong
     and no_too_much_lower_histogram
     and no_lower_bar_is_higher_or_stronger_than_start
     and crossed_at_least_ones_under_9_ema
     and current_bar_body_is_solid
     and current_bar_volume_is_solid

    if result
        label.new(bar_index-start_index, high[start_index], text=str.format("s: {0}.", start_index), size = size.small, style = label.style_label_lower_right)
        log.info("Change upwards! start index: {0}", start_index)

    result

change_upwards_indication = change_upwards_indication(0)

plotshape(change_upwards_indication, title="Change upwards", color=color.green, display = display.pane, style = shape.labeldown, size = size.small, location = location.abovebar, text = "📊")

alertcondition(change_upwards_indication, title="Change Upwards", message="Change Upwards")
