// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TheFirstPatienceTrader

indicator(title="Change Upwards", overlay = true, max_bars_back = 5000)
import TradingView/ta/10

//@version=6

relevant_timezone = "America/New_York"

ema_9 = ta.ema(close, 9)
ema_20 = ta.ema(close, 20)
vwap = ta.vwap(hlc3)
vol_avg = ta.sma(volume, 20)
[macd, signal_line, histogram] = ta.macd(close, 12, 26, 9)
current_timeframe = str.tonumber(timeframe.period)
if timeframe.period == "10S"
    current_timeframe := 10

_made_more_than_usual_percentage_already(index, percentage) =>
    yesterday_close = request.security(syminfo.tickerid, "D", close[1], lookahead = barmerge.lookahead_on)
    if (hour[index] == 9 and minute[index] < 30) or hour[index] < 9
        yesterday_close := request.security(syminfo.tickerid, "D", close, lookahead = barmerge.lookahead_on)
    (close[index] - yesterday_close)/open[index] > percentage

change_upwards_indication(index) =>
    percentage = 0.1
    after_market_starts_to_move = (hour[index] == 9 and minute[index] >= 30) or hour[index] > 9
    made_more_than_usual_percentage_already = _made_more_than_usual_percentage_already(index, percentage)
    bar_is_above_all_indicators = close[index] > ema_9[index]-0.01
     and close[index] > vwap[index]-0.01

    minutes_back_to_market_start = ((hour[index] - 7) * 60) + minute[index]

    bars_back = int(minutes_back_to_market_start/current_timeframe)

    start_index = 0
    for i = bars_back to index+1
        if i < 0
            continue
        volume_starts_to_move = volume[i] > volume[i+1] * 10
        price_starts_to_move = (high[i] - low[i]) > (high[i+1] - low[i+1]) * 2
        histogram_became_positive = histogram[i] > 0
         and (histogram[i+1] < 0
              or histogram[i] > histogram[i+1] * 5
              or (histogram[i+1] < histogram[i+2] and histogram[i+1] < histogram[i]))

        bar_is_positive = close[i] > open[i]
        volume_avg_has_changed = vol_avg[i] > vol_avg[i+1] * 2

        if true
         and volume_starts_to_move
         and price_starts_to_move
         and bar_is_positive
         and histogram_became_positive
         and volume_avg_has_changed
            start_index := i
            // if time == timestamp(relevant_timezone, year, 8, 25, 12, 00) and current_timeframe == 15
            //     log.info("i: {0}", i)
            break

    no_bar_before_has_bigger_volume = true
    for j = start_index + int(60/current_timeframe)*4 to start_index+1
        if close[j] > close[start_index]
            no_bar_before_has_bigger_volume := false
            break

    macd_before_is_positive_but_weaker = true
     and histogram[index+1] > 0
     and macd[index+1] > 0
     and signal_line[index+1] > 0
     and histogram[index] > histogram[index+1]
     and histogram[index+2] > histogram[index+1]

    histogram_was_positive_until_now = true
    for i = start_index to index
        if histogram[i] < 0
            histogram_was_positive_until_now := false
            break

    volume_is_stronger_than_before = true
     and volume[index] > volume[index+1]
     and volume[index] > 100000
     and volume[index+1] > 100000
     and volume[index] > vol_avg[index]

    for i = start_index to index
        if volume[i] < 20000
            volume_is_stronger_than_before := false

    most_of_move_already_happend = false
    for i = index to start_index
        if i-1 < 0
            continue
        momentum_change_downwards = histogram[i] > histogram[i+1]
         and histogram[i] > histogram[i-1]

        if momentum_change_downwards
            distance_from_start = start_index - i
            if distance_from_start > (i-1) * 3
                most_of_move_already_happend := true
                break

    only_on_higher_timeframes = current_timeframe >= 5

    result = true
     and after_market_starts_to_move
     and made_more_than_usual_percentage_already
     and bar_is_above_all_indicators
     and macd_before_is_positive_but_weaker
     and volume_is_stronger_than_before
     and only_on_higher_timeframes
     and histogram_was_positive_until_now
     and start_index != 0
     and not most_of_move_already_happend
     and no_bar_before_has_bigger_volume

    if result
        label.new(bar_index-start_index, high[start_index], text=str.format("s: {0}.", start_index), size = size.small, style = label.style_label_lower_right)
        log.info("Change upwards! start index: {0}", start_index)

    result

change_upwards_indication = change_upwards_indication(0)

plotshape(change_upwards_indication, title="Change upwards", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.belowbar, text = "📊")

alertcondition(change_upwards_indication, title="Positive indication for long/short momentum", message="Positive indication for long/short momentum")
