// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TheFirstPatienceTrader

indicator(title="Continues Trend", overlay = true, max_bars_back = 5000)
import TradingView/ta/10

//@version=6

relevant_timezone = "America/New_York"

ema_9 = ta.ema(close, 9)
vwap = ta.vwap(hlc3)
vol_avg = ta.sma(volume, 20)
[macd, signal_line, histogram] = ta.macd(close, 12, 26, 9)
current_timeframe = str.tonumber(timeframe.period)
if timeframe.period == "10S"
    current_timeframe := 10

bars_back = (((hour[0] - 4) * 60) + minute[0])/current_timeframe

// if time == timestamp(relevant_timezone, 2025, 9, 18, 11, 50) and current_timeframe == 5
//     log.info("some log")

_made_more_than_usual_percentage_already(index, percentage) =>
    yesterday_close = request.security(syminfo.tickerid, "D", close[1], lookahead = barmerge.lookahead_on)
    (close[index] - yesterday_close)/open[index] > percentage

_get_starting_index(index, with_threshold) =>
    starting_index = 0
    min_bars_back = math.min(bars_back, 40)
    for i = index+1 to index+min_bars_back
        if i < 0
            continue
        is_first_bar_to_pop_up = close[i] > open[i]
         and volume[i] > volume[i+1] * 1.5
         and volume[i] > vol_avg[i]
         and close[i] > ema_9[i]
         and high[i] > vwap[i]
         and high[i] - low[i] > (high[i+1] - low[i+1]) * 2
         and (close[i] - open[i])/(high[i] - low[i]) >= 0.3
         and dayofmonth[i] == dayofmonth[index]
         and high[i] > vwap[i]

        if with_threshold
            is_first_bar_to_pop_up := is_first_bar_to_pop_up
             and volume[i] > 40000

        if is_first_bar_to_pop_up
            for j = i+60 to i+1
                if dayofmonth[j] != dayofmonth[i]
                    continue

                if volume[j] >= volume[i]
                 and high[j] >= high[i]
                    is_first_bar_to_pop_up := false
                    break

                if volume[j]/volume[i] >= 0.75 and j - i < 10 and volume[j] > vol_avg[j] and with_threshold
                    is_first_bar_to_pop_up := false
                    break

                if volume[j]/volume[i] >= 0.6 and (high[j] - low[j])/(high[i] - low[i]) > 0.9
                    is_first_bar_to_pop_up := false
                    break

            if is_first_bar_to_pop_up
                starting_index := i
                break

    starting_index

_get_top_index(index, starting_index) =>
    highest_high = 0.0
    highest_high_index = 0
    for i = starting_index to index+2
        if high[i] > highest_high
            highest_high := high[i]
            highest_high_index := i

    top_index = 0
    for i = index to starting_index
        if i-1 < 0
            continue

        if high[i] > high[i+1]
         and high[i] > high[i-1]
         and close[i] > ema_9[i]
         and volume[i] > vol_avg[i]
         and high[i] == highest_high
            top_index := i
            break

    top_index

_get_lowest_point_from_top_point_index(index, top_index) =>
    lowest_point_from_top_point_value = 1000.0
    lowest_point_from_top_point_index = 0
    for i = index+1 to top_index-1
        if i < 0
            continue
        if low[i] < lowest_point_from_top_point_value
            lowest_point_from_top_point_value := low[i]
            lowest_point_from_top_point_index := i

    lowest_point_from_top_point_index

_move_is_still_strong_due_to_fibonacci_retracement(index, starting_index, top_index, lowest_point_from_top_point_index) =>
    fibonacci_retracement = (high[top_index] - low[lowest_point_from_top_point_index])/(high[top_index] - open[starting_index])
    move_is_still_strong_due_to_fibonacci_retracement = starting_index > top_index
     and fibonacci_retracement <= 0.62
     and fibonacci_retracement >= 0.3

    if not move_is_still_strong_due_to_fibonacci_retracement and top_index-1 > 0
        move_is_still_strong_due_to_fibonacci_retracement := close[index] > high[top_index-1]
         and fibonacci_retracement <= 0.8
         and fibonacci_retracement >= 0.3

    [move_is_still_strong_due_to_fibonacci_retracement, fibonacci_retracement]

_current_bar_should_be_involved_with_9_ema(index, top_index) =>
    distance_from_ema_9 = math.abs(ema_9[index] - open[index])/(high[index] - open[index])

    open_under_ema_9_but_bar_is_strong = true
     and open[index] <= ema_9[index]
     and math.abs(ema_9[index] - low[index])/(high[index] - low[index]) <= 0.10

    open_above_ema_9_but_close = true
     and open[index] > ema_9[index]
     and (low[index] - ema_9[index])/(high[index] - low[index]) <= 0.10

    ema_9_change_is_higher_than_before = true
     and ema_9[index] - ema_9[index+1] > ema_9[index+1] - ema_9[index+2]

    ema_9_change_from_top_index_is_highest = true
    current_change = ema_9[index] - ema_9[index+1]
    for i = top_index-1 to index+1
        if i < 0
            continue
        if ema_9[i] - ema_9[i+1] >= current_change
            ema_9_change_from_top_index_is_highest := false

    not_close_but_strong = ema_9_change_from_top_index_is_highest
     and histogram[index] > histogram[index+1]
     and histogram[index+2] > histogram[index+1]
     and histogram[index+3] > histogram[index+2]

    ema_9_change_is_higher_than_before
     and (open_under_ema_9_but_bar_is_strong or open_above_ema_9_but_close or not_close_but_strong)

_milestones_are_valid(index, starting_index, top_index) =>
    milestones_are_valid = true
     and starting_index != top_index
     and starting_index > index
     and top_index > index
     and starting_index > 0
     and top_index > 0

_histogram_looks_good(index, top_index) =>
    histogram_changed_direction = histogram[index] > histogram[index+1]
     and histogram[index+1] < histogram[index+2]

    histogram_raised_significantly = true
     and histogram[index+2] < histogram[index+1]
     and histogram[index+1] < histogram[index]
     and histogram[index+2]/histogram[index+1] >= 0.85
     and histogram[index] - histogram[index+1] > (histogram[index+1] - histogram[index+2]) * 2

    histogram_changed_significantly = histogram_changed_direction
     or histogram_raised_significantly

    histogram_changed_significantly
     and histogram[index]/histogram[top_index] >= 0.5

_current_bar_close_close_to_high(index) =>
    close[index]/high[index] >= 0.7

_most_of_current_body_is_above_9_ema(index) =>
    most_of_current_body_is_above_9_ema = open[index] >= ema_9[index]
    if not most_of_current_body_is_above_9_ema
        most_of_current_body_is_above_9_ema := (ema_9[index] - open[index])/(high[index] - open[index]) <= 0.2

    most_of_current_body_is_above_9_ema
     and ema_9[index]/low[index] > 0.95

_current_volume_is_strong_with_high_volume(index, top_index) =>
    current_volume_is_strong_with_high_volume = true
     and close[index] > open[index]
     and low[index]/open[index] > 0.98
     and (close[index] - open[index])/(high[index] - low[index]) >= 0.6

    for i = top_index-1 to index
        if i < 0
            continue

        if volume[index]/volume[i] < 0.8
            current_volume_is_strong_with_high_volume := false
            break

    current_volume_is_strong_with_high_volume

_most_of_bars_are_volatile(starting_index, index) =>
    volatile_bars = 0
    for i = starting_index to index
        if volume[i] >= 40000
            volatile_bars += 1

    most_of_bars_are_volatile = volatile_bars/starting_index >= 0.6

    most_of_bars_are_volatile

_histogram_is_positive_until_now(starting_index, index) =>
    histogram_is_positive_until_now = true
    for i = starting_index to index
        if histogram[i] < 0
            histogram_is_positive_until_now := false
            break

    top_histogram_index = 0
    top_histogram_value = 0.0
    for i = starting_index to index+1
        if histogram[i] > top_histogram_value
            top_histogram_value := histogram[i]
            top_histogram_index := i

    histogram_top_appears_count = 0
    for i = top_histogram_index to index+1
        if i-1 < 0
            continue

        if histogram[i] > histogram[i-1]
         and histogram[i] > histogram[i+1]
         and i > index
         and i < top_histogram_index
            histogram_top_appears_count += 1

    [histogram_is_positive_until_now and histogram_top_appears_count < 2, top_histogram_index]

_histogram_changed_direction(index) =>
    histogram[index] > histogram[index+1]
     and histogram[index+1] < histogram[index+2]

_negative_bars_volume_is_going_down(starting_index, index) =>
    negative_bars_volume_is_going_down = true
    for i = starting_index-1 to index
        if i < 0
            continue
        if close[i] < open[i]
         and close[i+1] < open[i+1]
         and volume[i] >= volume[i+1]
            negative_bars_volume_is_going_down := false
            break

    negative_bars_volume_is_going_down

_negative_bars_are_weak(top_index, index) =>
    negative_bars_are_weak = true
    for i = top_index-1 to index
        if i < 0
            continue

        if close[i] < open[i]
         and close[i+1] > open[i+1]
         and volume[i] > volume[i+1]
         and volume[i] > vol_avg[i]
            negative_bars_are_weak := false
            break

        if close[i] < open[i]
         and volume[i] > vol_avg[i]
         and low[i]/close[i] > 0.95
         and (high[i] - open[i])/(high[i] - low[i]) >= 0.4
            negative_bars_are_weak := false

    negative_bars_are_weak

_retracement_should_be_long_enough(index, top_index) =>
    base_condition = top_index >= 3
    retracement_should_be_long_enough = true
    for i = top_index to index+1
        if close[i] > open[i]
            retracement_should_be_long_enough := false
            break

    retracement_should_be_long_enough or base_condition

_starting_index_is_not_the_biggest_bar(index, starting_index) =>
    starting_index_is_not_the_biggest_bar = false
    for i = starting_index-1 to index
        if i < 0
            continue

        if volume[i] >= volume[starting_index]
            starting_index_is_not_the_biggest_bar := true
            break

    starting_index_is_not_the_biggest_bar

_volume_sum_is_positive(index, starting_index, positive_volume_bigger_by_percentage) =>
    positive_volume_sum = 0.0
    negative_volume_sum = 0.0

    for i = starting_index to index
        if close[i] > open[i]
            positive_volume_sum += volume[i]
        else
            negative_volume_sum += volume[i]

    result = positive_volume_sum > negative_volume_sum
    if positive_volume_bigger_by_percentage > 0.0
        result := negative_volume_sum/positive_volume_sum < positive_volume_bigger_by_percentage

    result

_current_bar_crossed_finally_highest_high(index, top_index, starting_index) =>
    current_bar_crossed_finally_highest_high = close[index] > high[top_index]
    attempts_indexes = array.new_int()

    for i = starting_index to index+1
        if high[i]/high[top_index] >= 0.96
         and (close[i] - low[i])/(high[i] - low[i]) <= 0.7
            array.push(attempts_indexes, i)

    current_bar_crossed_finally_highest_high := true
     and current_bar_crossed_finally_highest_high
     and array.size(attempts_indexes) >= 2

    [current_bar_crossed_finally_highest_high, attempts_indexes]

_no_more_than_2_retracements_until_now(index, starting_index, top_index) =>
    retracement_indexes = array.new_int()
    for i = starting_index-1 to index
        if i-1 < 0 or i < 0
            continue

        if low[i] > low[i+1] and low[i] < low[i-1]
            continue

        retracement_case_1 = true
         and high[i] < high[i+1]
         and high[i] < high[i-1]
         and close[i-1] > open[i-1]
         and (low[i] <= ema_9[i] or ema_9[i]/low[i] >= 0.9)

        retracement_case_2 = true
         and high[i] < high[i+1]
         and low[i] < low[i+1]
         and low[i] < low[i-1]
         and close[i-1] > open[i-1]
         and (low[i] <= ema_9[i] or ema_9[i]/low[i] >= 0.9)

        retracement_case_3 = true
         and high[i] < high[i+1]
         and high[i] < high[i-1]
         and (close[i] - low[i])/(high[i] - low[i]) > 0.5
         and (open[i] - low[i])/(high[i] - low[i]) > 0.5
         and low[i] < low[i+1]
         and low[i] < low[i-1]

        retracement_case_4 = true
         and high[i] < high[i+1]
         and low[i] < low[i+1]
         and low[i] < low[i-1]
         and low[i] - ema_9[i] < low[i+1] - ema_9[i+1]
         and low[i] - ema_9[i] < low[i-1] - ema_9[i-1]
         and (close[i] - low[i])/(high[i] - low[i]) > 0.5
         and (open[i] - low[i])/(high[i] - low[i]) > 0.5
         and volume[i] < volume[i+1]

        retracement_case_5 = true
         and i < top_index
         and i > index
         and low[i] < low[i+1]
         and low[i] < low[i-1]
         and ema_9[i]/low[i] >= 0.99
         and i-1 == index

        result = (retracement_case_1
         or retracement_case_2
         or retracement_case_3
         or retracement_case_4
         or retracement_case_5)

        if result
            if not array.includes(retracement_indexes, i+1)
                array.push(retracement_indexes, i)

    retracements_count = array.size(retracement_indexes)
    [retracements_count <= 2 and retracements_count >= 1, retracement_indexes]

_current_bar_high_close_to_top_high(index, top_index, starting_index) =>
    base_condition = high[index]/high[top_index] >= 0.99
    current_bar_high_close_to_top_high = true
    for i = starting_index to index+1
        if close[i] > close[index]
            current_bar_high_close_to_top_high := false
            break

    current_bar_high_close_to_top_high or base_condition

_most_of_volume_are_stuck_between_top_index_to_current(index, top_index, starting_index) =>
    all_volume_from_movement = 0.0
    for i = starting_index to index
        all_volume_from_movement += volume[i]

    volume_from_top_index = 0.0
    for i = top_index to index
        volume_from_top_index += volume[i]

    volume_percentage_from_top = volume_from_top_index/all_volume_from_movement
    bars_percentage_from_top = top_index/starting_index

    most_of_volume_are_stuck_between_top_index_to_current = bars_percentage_from_top/volume_percentage_from_top < 0.9

    [most_of_volume_are_stuck_between_top_index_to_current, volume_percentage_from_top, bars_percentage_from_top]

_too_many_tops_with_rejections_in_range_of_current_bar(index, starting_index, top_index) =>
    tops_with_rejection_indexes = array.new_int()
    for i = starting_index to index+1
        if high[i] < open[index]
            continue

        if true
         and high[i] > open[index]
         and high[i] < high[index]
         and close[i] < open[i]
         and (high[i] - open[i])/(high[i] - low[i]) >= 0.25
            array.push(tops_with_rejection_indexes, i)
            continue

        if true
         and high[i] > open[index]
         and high[i] < high[index]
         and close[i] < high[i]
         and (((high[i] - close[i])/(high[i] - low[i]) >= 0.25 and close[i] > open[i]) or ((high[i] - open[i])/(high[i] - low[i]) >= 0.25 and close[i] < open[i]))
         and volume[i] > vol_avg[i]
            array.push(tops_with_rejection_indexes, i)

    rejections_count = array.size(tops_with_rejection_indexes)
    too_many_tops_with_rejections_in_range_of_current_bar = rejections_count/starting_index > 0.5
     or rejections_count > 3

    [too_many_tops_with_rejections_in_range_of_current_bar, tops_with_rejection_indexes]

_bar_with_most_volume_is_with_big_rejection_inside_range_of_current_body(index, starting_index, top_index) =>
    most_volatile_bar_index = 0
    most_volume_bar = 0.0
    for i = starting_index to index+1
        if volume[i] > most_volume_bar
         and i != top_index
            most_volume_bar := volume[i]
            most_volatile_bar_index := i

    bar_with_most_volume_is_with_big_rejection_inside_range_of_current_body = true
     and volume[most_volatile_bar_index] > volume[index]
     and high[most_volatile_bar_index] < high[index]
     and high[most_volatile_bar_index] > open[index]
     and (high[most_volatile_bar_index] - close[most_volatile_bar_index])/(high[most_volatile_bar_index] - open[most_volatile_bar_index]) > 0.5
     and starting_index - most_volatile_bar_index > most_volatile_bar_index

    bar_with_most_volume_is_with_big_rejection_inside_range_of_current_body

_indecision_histogram_from_top(index, top_index) =>
    indecision_histogram_from_top = false
    for i = top_index-1 to index
        if i < 0 or i-1 < 0
            continue

        if true
         and histogram[i] > histogram[i+1]
         and histogram[i] > histogram[i-1]
         and histogram[i+2] > histogram[i+1]
            indecision_histogram_from_top := true
            break

    indecision_histogram_from_top

_current_bar_is_top_and_after_own_retracement(index, top_index) =>
    current_bar_is_highest = high[index] >= high[top_index]
    current_bar_after_retracement = true
     and (open[index] - low[index])/(high[index] - low[index]) >= 0.25
     and (high[index] - close[index])/(high[index] - low[index]) <= 0.2
     and close[index] - open[index] > high[index] - close[index]

    current_bar_volume_is_higher_than_before = volume[index] > volume[index+1]
     and volume[index] > vol_avg[index]

    ema_9_close_to_low = ema_9[index]/low[index] >= 0.99

    result = true
     and current_bar_is_highest
     and current_bar_after_retracement
     and current_bar_volume_is_higher_than_before
     and ema_9_close_to_low

    result

_current_bar_is_halted(index) =>
    current_bar_is_halted = true
     and close[index] == high[index]
     and close[index] - open[index] > (close[index+1] - open[index+1]) * 2
     and (high[index] - high[index+1])/(high[index+1] - low[index+1]) >= 0.5
     and high[index+1] - low[index+1] >= 0.1
     and close[index] > vwap[index]
     and close[index] > ema_9[index]
     and histogram[index] > 0
     and volume[index] > 5000

_current_bar_is_highest_for_halted(index, starting_index, top_index) =>
    current_bar_is_highest_for_halted = true
    for i = starting_index to index+1
        if high[i] > high[index]
            current_bar_is_highest_for_halted := false
            break

    milestones_are_valid = _milestones_are_valid(index, starting_index, top_index)

    current_bar_is_highest_for_halted and milestones_are_valid

_higher_than_before(index) =>
    high[index] > high[index+1]

_first_retracement_came_too_late(starting_index, top_index, retracement_indexes) =>
    first_retracement = 0
    for retracement in retracement_indexes
        if retracement > first_retracement
            first_retracement := retracement

    retracement_attempts = 0
    for i = starting_index to top_index
        if true
         and (open[i] - low[i])/(high[i] - low[i]) >= 0.25
         and volume[i] > vol_avg[i]
         and open[i] - low[i] > high[i] - close[i]
            retracement_attempts += 1

    first_retracement_came_too_late = first_retracement/starting_index < 0.4
     and starting_index >= 10
     and retracement_attempts < 2

    first_retracement_came_too_late

_current_session_has_at_least_one_red_bar(index, starting_index) =>
    current_session_has_at_least_one_red_bar = false
    for i = starting_index to index+1
        if close[i] < open[i]
            current_session_has_at_least_one_red_bar := true
            break

    current_session_has_at_least_one_red_bar

_current_bar_is_full(index) =>
    current_bar_is_full = (close[index] - open[index])/(high[index] - low[index]) >= 0.4
    current_bar_is_full

_current_bar_is_highest_and_full(index, starting_index) =>
    current_bar_is_highest = true
    for i = starting_index to index+1
        if high[i] >= high[index]
            current_bar_is_highest := false
            break

    current_bar_is_full = (close[index] - open[index])/(high[index] - low[index]) >= 0.8
     and low[index]/open[index] >= 0.95

    current_bar_is_highest
     and current_bar_is_full

_most_session_is_before_top_index(starting_index, top_index) =>
    top_index/starting_index <= 0.7

_retracement_is_strong_but_graph_still_good(index, fibonacci_retracement, starting_index) =>
    positive_histogram = 0
    negative_histogram = 0
    for i = starting_index to index
        if histogram[i] > histogram[i+1]
            positive_histogram += 1
        else
            negative_histogram += 1

    histogram_is_positive_at_most = negative_histogram/positive_histogram <= 0.5
    price_jumps_on_current_bar = (high[index+1] - low[index+1])/(high[index] - low[index]) < 0.5
     and close[index] > open[index]
     and low[index+1]/low[index] >= 0.9


    retracement_is_strong_but_graph_still_good = true
     and fibonacci_retracement > 0.8
     and histogram_is_positive_at_most
     and price_jumps_on_current_bar

    retracement_is_strong_but_graph_still_good

_big_retracement_between_top_to_start(starting_index, top_index) =>
    big_retracement_between_top_to_start = false
    for i = starting_index-1 to top_index
        if i < 0
            continue
        if low[i] < low[starting_index]
            big_retracement_between_top_to_start := true
            break

        if low[starting_index]/low[i] >= 0.99
            big_retracement_between_top_to_start := true
            break

    big_retracement_between_top_to_start

///////////// Indications /////////////
base_case_check(index) =>
    starting_index = _get_starting_index(index, true)
    top_index = _get_top_index(index, starting_index)

    percentage = 0.1
    made_more_than_usual_percentage_already = _made_more_than_usual_percentage_already(index, percentage)
    movement_is_after_market_start = hour[index] >= 9 and hour[index] <= 20
    current_bar_close_close_to_high = _current_bar_close_close_to_high(index)
    current_bar_high_close_to_top_high = _current_bar_high_close_to_top_high(index, top_index, starting_index)
    milestones_are_valid = _milestones_are_valid(index, starting_index, top_index)
    lowest_point_from_top_point_index = _get_lowest_point_from_top_point_index(index, top_index)
    current_volume_is_strong_with_high_volume = _current_volume_is_strong_with_high_volume(index, top_index)
    most_of_bars_are_volatile = _most_of_bars_are_volatile(starting_index, index)
    [histogram_is_positive_until_now, top_histogram_index] = _histogram_is_positive_until_now(starting_index, index)
    [no_more_than_2_retracements_until_now, retracement_indexes] = _no_more_than_2_retracements_until_now(index, starting_index, top_index)
    bar_with_most_volume_is_with_big_rejection_inside_range_of_current_body = _bar_with_most_volume_is_with_big_rejection_inside_range_of_current_body(index, starting_index, top_index)
    indecision_histogram_from_top = _indecision_histogram_from_top(index, top_index)
    higher_than_before = _higher_than_before(index)
    current_session_has_at_least_one_red_bar = _current_session_has_at_least_one_red_bar(index, starting_index)
    current_bar_is_full = _current_bar_is_full(index)
    big_retracement_between_top_to_start = _big_retracement_between_top_to_start(starting_index, top_index)

    base_indication = true
     and made_more_than_usual_percentage_already
     and movement_is_after_market_start
     and current_bar_close_close_to_high
     and milestones_are_valid
     and most_of_bars_are_volatile
     and histogram_is_positive_until_now
     and no_more_than_2_retracements_until_now
     and current_bar_high_close_to_top_high
     and not bar_with_most_volume_is_with_big_rejection_inside_range_of_current_body
     and not indecision_histogram_from_top
     and higher_than_before
     and current_session_has_at_least_one_red_bar
     and current_bar_is_full
     and not big_retracement_between_top_to_start

    [base_indication, starting_index, top_index, lowest_point_from_top_point_index, top_histogram_index, retracement_indexes]

cases(index) =>
    main_case = false
    [base_indication, starting_index, top_index, lowest_point_from_top_point_index, top_histogram_index, retracement_indexes] = base_case_check(index)
    negative_bars_are_weak = _negative_bars_are_weak(top_index, index)
    [move_is_still_strong_due_to_fibonacci_retracement, fibonacci_retracement] = _move_is_still_strong_due_to_fibonacci_retracement(index, starting_index, top_index, lowest_point_from_top_point_index)
    retracement_should_be_long_enough = _retracement_should_be_long_enough(index, top_index)
    most_of_current_body_is_above_9_ema = _most_of_current_body_is_above_9_ema(index)
    current_volume_is_strong_with_high_volume = _current_volume_is_strong_with_high_volume(index, top_index)
    starting_index_is_not_the_biggest_bar = _starting_index_is_not_the_biggest_bar(index, starting_index)
    negative_bars_volume_is_going_down = _negative_bars_volume_is_going_down(starting_index, index)
    [current_bar_crossed_finally_highest_high, attempts_indexes] = _current_bar_crossed_finally_highest_high(index, top_index, starting_index)
    volume_sum_is_positive = _volume_sum_is_positive(index, starting_index, 0.0)
    current_bar_is_top_and_after_own_retracement = _current_bar_is_top_and_after_own_retracement(index, top_index)
    histogram_changed_direction = _histogram_changed_direction(index)
    [most_of_volume_are_stuck_between_top_index_to_current, volume_percentage_from_top, bars_percentage_from_top] = _most_of_volume_are_stuck_between_top_index_to_current(index, top_index, starting_index)
    [too_many_tops_with_rejections_in_range_of_current_bar, tops_with_rejection_indexes] = _too_many_tops_with_rejections_in_range_of_current_bar(index, starting_index, top_index)
    current_bar_is_highest_and_full = _current_bar_is_highest_and_full(index, starting_index)
    first_retracement_came_too_late = _first_retracement_came_too_late(starting_index, top_index, retracement_indexes)
    most_session_is_before_top_index = _most_session_is_before_top_index(starting_index, top_index)
    retracement_is_strong_but_graph_still_good = _retracement_is_strong_but_graph_still_good(index, fibonacci_retracement, starting_index)

    winning_cases = array.new_string()

    case_1 = true
     and base_indication
     and volume_sum_is_positive
     and negative_bars_are_weak
     and most_of_current_body_is_above_9_ema
     and current_volume_is_strong_with_high_volume
     and negative_bars_volume_is_going_down
     and histogram_changed_direction
     and not most_of_volume_are_stuck_between_top_index_to_current
     and not too_many_tops_with_rejections_in_range_of_current_bar
     and move_is_still_strong_due_to_fibonacci_retracement
     and retracement_should_be_long_enough

    if case_1
        array.push(winning_cases, "case 1")
        main_case := case_1

    case_2 = true
     and base_indication
     and volume_sum_is_positive
     and most_of_current_body_is_above_9_ema
     and current_volume_is_strong_with_high_volume
     and negative_bars_volume_is_going_down
     and histogram_changed_direction
     and not most_of_volume_are_stuck_between_top_index_to_current
     and not too_many_tops_with_rejections_in_range_of_current_bar
     and move_is_still_strong_due_to_fibonacci_retracement
     and retracement_should_be_long_enough

    if case_2
        array.push(winning_cases, "case 2")
        main_case := case_2

    case_3 = true
     and base_indication
     and volume_sum_is_positive
     and starting_index_is_not_the_biggest_bar
     and negative_bars_volume_is_going_down
     and fibonacci_retracement > 0.4
     and fibonacci_retracement < 0.5
     and histogram_changed_direction
     and not most_of_volume_are_stuck_between_top_index_to_current
     and not too_many_tops_with_rejections_in_range_of_current_bar
     and move_is_still_strong_due_to_fibonacci_retracement
     and retracement_should_be_long_enough

    if case_3
        array.push(winning_cases, "case 3")
        main_case := case_3

    case_4 = true
     and base_indication
     and volume_sum_is_positive
     and starting_index_is_not_the_biggest_bar
     and current_bar_crossed_finally_highest_high
     and fibonacci_retracement > 0.4
     and fibonacci_retracement < 0.5
     and histogram_changed_direction
     and not most_of_volume_are_stuck_between_top_index_to_current
     and not too_many_tops_with_rejections_in_range_of_current_bar
     and move_is_still_strong_due_to_fibonacci_retracement
     and retracement_should_be_long_enough

    if case_4
        array.push(winning_cases, "case 4")
        main_case := case_4

    _volume_sum_is_positive = _volume_sum_is_positive(index, starting_index, 0.5)
    case_5 = true
     and base_indication
     and _volume_sum_is_positive
     and starting_index_is_not_the_biggest_bar
     and negative_bars_volume_is_going_down
     and fibonacci_retracement > 0.3
     and fibonacci_retracement < 0.5
     and starting_index >= 8
     and histogram_changed_direction
     and not most_of_volume_are_stuck_between_top_index_to_current
     and not too_many_tops_with_rejections_in_range_of_current_bar
     and move_is_still_strong_due_to_fibonacci_retracement
     and retracement_should_be_long_enough

    if case_5
        array.push(winning_cases, "case 5")
        main_case := case_5

    case_6 = true
     and base_indication
     and _volume_sum_is_positive
     and starting_index_is_not_the_biggest_bar
     and fibonacci_retracement > 0.5
     and fibonacci_retracement < 0.72
     and array.size(retracement_indexes) == 1
     and histogram_changed_direction
     and not most_of_volume_are_stuck_between_top_index_to_current
     and not too_many_tops_with_rejections_in_range_of_current_bar
     and move_is_still_strong_due_to_fibonacci_retracement
     and retracement_should_be_long_enough

    if case_6
        array.push(winning_cases, "case 6")
        main_case := case_6

    case_7 = true
     and base_indication
     and current_bar_is_top_and_after_own_retracement
     and move_is_still_strong_due_to_fibonacci_retracement
     and retracement_should_be_long_enough

    if case_7
        array.push(winning_cases, "case 7")
        main_case := case_7

    case_8 = true
     and base_indication
     and histogram_changed_direction
     and current_bar_is_highest_and_full
     and volume_sum_is_positive
     and most_of_current_body_is_above_9_ema
     and starting_index_is_not_the_biggest_bar
     and not first_retracement_came_too_late
     and most_session_is_before_top_index
     and move_is_still_strong_due_to_fibonacci_retracement
     and retracement_should_be_long_enough

    if case_8
        array.push(winning_cases, "case 8")
        main_case := case_8

    case_9 = true
     and base_indication
     and negative_bars_are_weak
     and most_of_current_body_is_above_9_ema
     and current_volume_is_strong_with_high_volume
     and starting_index_is_not_the_biggest_bar
     and negative_bars_volume_is_going_down
     and current_bar_crossed_finally_highest_high
     and volume_sum_is_positive
     and histogram_changed_direction
     and retracement_is_strong_but_graph_still_good

    if case_9
        array.push(winning_cases, "case 9")
        main_case := case_9

    ////////////       HALTED CASE       //////////// --- variables new initialization!
    _starting_index = _get_starting_index(index, false)
    _top_index = _get_top_index(index, _starting_index)
    _retracement_should_be_long_enough = _retracement_should_be_long_enough(index, _top_index)
    made_more_than_usual_percentage_already = _made_more_than_usual_percentage_already(index, 0.1)
    movement_is_after_market_start = hour[index] >= 9 and hour[index] <= 20
    _lowest_point_from_top_point_index = _get_lowest_point_from_top_point_index(index, top_index)
    [_move_is_still_strong_due_to_fibonacci_retracement, _fibonacci_retracement] = _move_is_still_strong_due_to_fibonacci_retracement(index, _starting_index, _top_index, _lowest_point_from_top_point_index)
    negative_bars_are_weak := _negative_bars_are_weak(_top_index, index)
    most_of_current_body_is_above_9_ema := _most_of_current_body_is_above_9_ema(index)
    current_bar_is_halted = _current_bar_is_halted(index)
    current_bar_is_highest_for_halted = _current_bar_is_highest_for_halted(index, starting_index, top_index)

    halted_case = true
     and made_more_than_usual_percentage_already
     and movement_is_after_market_start
     and (_move_is_still_strong_due_to_fibonacci_retracement or current_bar_is_highest_for_halted)
     and most_of_current_body_is_above_9_ema
     and _retracement_should_be_long_enough
     and current_bar_is_halted

    if halted_case
        starting_index := _starting_index
        top_index := _top_index
        fibonacci_retracement := _fibonacci_retracement
        lowest_point_from_top_point_index := _lowest_point_from_top_point_index

        array.push(winning_cases, "HALTED SYMBOL! halted case")
        main_case := halted_case

    for case in winning_cases
        log.info("{0}. starting_index: {1}. top_index: {2}.", case, starting_index, top_index)

    [main_case, fibonacci_retracement, starting_index, top_index, top_histogram_index, lowest_point_from_top_point_index, attempts_indexes, retracement_indexes, volume_percentage_from_top, bars_percentage_from_top, tops_with_rejection_indexes]

[main_case, fibonacci_retracement, starting_index, top_index, top_histogram_index, lowest_point_from_top_point_index, attempts_indexes, retracement_indexes, volume_percentage_from_top, bars_percentage_from_top, tops_with_rejection_indexes] = cases(0)
if main_case
    confirmation_label = label.new(bar_index, high, text = "✅", size = size.tiny)
    label.set_tooltip(confirmation_label, str.format("starting_index: {0}. top_index: {1}. fibonacci_retracement: {2}. lowest_point_from_top_point_index: {3}. top_histogram_index: {4}. attempts_indexes: {5}. retracement_indexes: {6}. volume_percentage_from_top: {7}. bars_percentage_from_top: {8}. tops_with_rejection_indexes: {9}", starting_index, top_index, fibonacci_retracement, lowest_point_from_top_point_index, top_histogram_index, attempts_indexes, retracement_indexes, volume_percentage_from_top, bars_percentage_from_top, tops_with_rejection_indexes))

plotshape(main_case, title="winning case", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.belowbar, text = "💰")

plot(fibonacci_retracement, "fibonacci_retracement", display = display.status_line)
plot(starting_index, "starting_index", display = display.status_line)
plot(top_index, "top_index", display = display.status_line)

alertcondition(main_case, title="Positive indication for long/short momentum", message="Positive indication for long/short momentum")
