// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TheFirstPatienceTrader

indicator(title="Continues Trend", overlay = true, max_bars_back = 5000)
import TradingView/ta/10

//@version=6

relevant_timezone = "America/New_York"

////           Reversal Indication           ////
reversal_sign = "🌠"
ema_9 = ta.ema(close, 9)
ema_20 = ta.ema(close, 20)
vwap = ta.vwap(hlc3)
vol_avg = ta.sma(volume, 20)
ema_200_days = request.security(syminfo.tickerid, "D", ema_9, lookahead = barmerge.lookahead_on)

bar_is_acting_as_reversal_upwards(index) =>
    [macd, signal, histogram] = ta.macd(close, 12, 26, 9)

    ema_9_is_above_all = ema_9[index] >= vwap[index] and ema_9[index] > ema_20[index]
    close_is_above_all = close[index] > open[index] and close[index] > ema_9[index]
    bar_before_is_red = close[index+1] < open[index+1]
    bar_volume_is_similar_to_bar_before = (high[index] - low[index])/(high[index+1]-low[index+1]) >= 0.65
    current_bar_is_positive = close[index] > open[index] and high[index] > close[index]
    current_bar_is_still_lower_than_bar_before = high[index] <= high[index+1]
    bar_has_inverted_hammer_pattern = (open[index] == low[index] or (open[index] - low[index])/(high[index] - low[index]) <= 0.2) and (high[index] - close[index])/(close[index] - low[index]) >= 0.3
    current_bar_is_close_to_9_ema = (low[index] - ema_9[index]) < (high[index]-low[index])
    most_of_the_bar_is_above_ema_9 = (math.abs(ema_9[index] - open[index])/(close[index] - open[index]) <= 0.5) or open[index] >= ema_9[index]
    bar_is_volatile = volume[index] > 50000
    macd_is_positive = histogram[index] > 0 and macd[index] > 0

    current_timeframe = str.tonumber(timeframe.period)
    bars_back = int(30/current_timeframe)

    weak_bar_found = false
    for i = index+bars_back to index
        bar_is_under_9_ema = open[i] < ema_9[i] and close[i] < ema_9[i] and volume[i] > volume[index]
        bar_is_under_vwap = open[i] < vwap[i] and close[i] < vwap[i] and volume[i] > volume[index]
        if bar_is_under_9_ema or bar_is_under_vwap
            weak_bar_found := true
            break

    high_before_is_low_than_high_before = true
    if current_timeframe <= 2
        high_before_is_low_than_high_before := high[index+1] < high[index+2]

    result = bar_before_is_red
     and bar_volume_is_similar_to_bar_before
     and current_bar_is_positive
     and current_bar_is_still_lower_than_bar_before
     and bar_has_inverted_hammer_pattern
     and current_bar_is_close_to_9_ema
     and most_of_the_bar_is_above_ema_9
     and bar_is_volatile
     and not weak_bar_found
     and high_before_is_low_than_high_before
     and macd_is_positive

    if current_timeframe <= 5
        result := result
         and ema_9_is_above_all
         and close_is_above_all

    result


////           Changing up Indication           ////
current_bar_is_in_volume_trend(index, trend_started_bar_index, vol_avg, vwap) =>
    green_bars_counter = 0
    green_bars_volume_counter = 0.0
    red_bars_counter = 0
    red_bars_volume_counter = 0.0
    bars_above_1000_counter = 0
    for i = trend_started_bar_index to index
        if volume[i] > 1000
            bars_above_1000_counter += 1
        if close[i] >= open[i]
            green_bars_counter += 1
            green_bars_volume_counter += volume[i]
        else
            red_bars_counter += 1
            red_bars_volume_counter += volume[i]

    most_bars_above_1000 = bars_above_1000_counter/trend_started_bar_index > 0.9

    nearest_green_bars_counter = 0
    nearest_red_bars_counter = 0
    nearest_green_bars_volume_counter = 0.0
    nearest_red_bars_volume_counter = 0.0
    for i = math.floor(trend_started_bar_index/2) to index
        if close[i] >= open[i]
            nearest_green_bars_counter += 1
            nearest_green_bars_volume_counter += volume[i]
        else if close[i] < open[i] and close[i] > vwap[i]
            nearest_red_bars_counter += 1
            nearest_red_bars_volume_counter += volume[i]

    calculated_vol_avg = 0.0
    for i = trend_started_bar_index to index
        calculated_vol_avg += vol_avg[i]

    vol_avg_is_above_threshold = calculated_vol_avg/trend_started_bar_index >= 2000

    volume_change_is_higher = true
    current_volume_change = volume[index] - volume[index+1]
    for i = trend_started_bar_index-1 to index+1
        if i-1 < 0 or index-1 < 0
            continue
        volume_change = volume[i] - volume[i+1]
        current_volume_change_after_is_lower = volume[index-1] < volume[i-1]
        if volume_change > current_volume_change and current_volume_change_after_is_lower
            volume_change_is_higher := false
            break

    volume_is_not_strong_enough = false
    at_least_one_low_is_lower_than_close_before = false
    for i = trend_started_bar_index-1 to index+1
        if i-1 < 0
            continue
        if volume[index] <= volume[i] * 1.5
            volume_is_not_strong_enough := true
        if low[i] < close[i+1]
            at_least_one_low_is_lower_than_close_before := true


    first_option = nearest_green_bars_volume_counter > nearest_red_bars_volume_counter
     and nearest_green_bars_counter >= nearest_red_bars_counter

    second_option = (nearest_green_bars_counter/nearest_red_bars_counter) > (green_bars_counter/red_bars_counter)
     and (nearest_green_bars_volume_counter/nearest_red_bars_volume_counter) > (green_bars_volume_counter/red_bars_volume_counter)

    // if time == timestamp(relevant_timezone, 2025, 7, 3, 10, 00) and timeframe.period == "5"
    //     log.info("nearest_green_bars_counter: {0}. nearest_red_bars_counter: {1}. nearest_green_bars_volume_counter: {2}. nearest_red_bars_volume_counter: {3}. vol_avg_is_above_threshold: {4}", nearest_green_bars_counter, nearest_red_bars_counter, nearest_green_bars_volume_counter, nearest_red_bars_volume_counter, calculated_vol_avg/trend_started_bar_index)

    vol_avg_is_above_threshold
     and most_bars_above_1000
     and volume_change_is_higher
     and not volume_is_not_strong_enough
     and at_least_one_low_is_lower_than_close_before
     and (first_option or second_option)

get_trend_started_bar_index(index, vwap, ema_9, vol_avg) =>
    [macd, signal_line, histogram] = ta.macd(close, 12, 26, 9)
    trend_started_bar_index = 0

    for i = index+49 to index+1
        if hour[i] < 7 or volume[i] < 5000 or histogram[i] < 0
            continue

        if i-1 < 0
            continue
        if low[i-1] < low[i]
            continue

        current_bar_is_weak = false
        for j = i+10 to i+1
            price_is_higher = high[j] - low[j] > high[i] - low[i] and high[i] < high[j]
            if price_is_higher
                current_bar_is_weak := true
                break

        if current_bar_is_weak
            continue

        if dayofmonth[i] != dayofmonth[index] or hour[i] < 7
            continue

        crossed_vwap_upwards = (low[i] < vwap[i] and close[i] > vwap[i] and vwap[i] > ema_9[i])
         or (low[i+1] < vwap[i+1] and close[i+1] > vwap[i+1] and vwap[i+1] > ema_9[i+1])
         or (low[i+2] < vwap[i+2] and close[i+2] > vwap[i+2] and vwap[i+2] > ema_9[i+2])

        bar_is_strong = (close[i] - open[i])/(high[i] - low[i]) >= 0.6
        if i-1 > 0 and not bar_is_strong
            bar_is_strong := (close[i-1] - open[i-1])/(high[i-1] - low[i-1]) >= 0.4
        bar_is_positive = close[i] > open[i]
        bar_is_volatile = volume[i] > vol_avg[i] and volume[i] > volume[i+1] and vol_avg[i] > vol_avg[i+1]
        bar_value_is_volatile = (high[i]-low[i]) > (high[i+1]-low[i+1]) * 2 or (close[i] - open[i]) > (close[i+1] - open[i+1])
        if crossed_vwap_upwards
         and bar_is_positive
         and bar_is_volatile
         and bar_value_is_volatile
         and bar_is_strong
            trend_started_bar_index := i
            break

        close_is_above_vwap = close[i] > vwap[i]
        if not crossed_vwap_upwards
         and close_is_above_vwap
         and hour[i] > 9
         and bar_is_positive
         and bar_is_volatile
         and bar_value_is_volatile
         and bar_is_strong
            trend_started_bar_index := i
            break

        if close_is_above_vwap
         and bar_value_is_volatile
         and close[i] > open[i]
         and volume[i] > volume[i+1] * 8
         and volume[i] >= 50000
         and bar_is_strong
            trend_started_bar_index := i
            break

    trend_started_bar_index

bar_ema_is_changing_up(index) =>
    volume_has_changed = volume[index] > volume[index+1]
    price_has_changed = close[index] - open[index] > math.abs(close[index+1] - open[index+1]) * 2 and close[index] > close[index+1] and high[index] - open[index] > 0.05
    lows_above_ema = low[index] > ema_9[index]-0.05 and low[index+1] > ema_9[index+1]-0.05
    bar_before_didnt_do_much = math.abs(close[index+1] - open[index+1])/(high[index+2] - low[index+2]) <= 0.5
    bar_before_price_movement_was_low = (high[index+1] - low[index+1])/open[index] <= 0.1 or math.abs(close[index+1] - low[index+1])/(high[index+1] - low[index+1]) <= 0.4
    current_bar_closed_strong = (close[index] - open[index])/(high[index] - low[index]) >= 0.4

    price_above_ema_for_last_bars = true
    for i = index+4 to index
        is_green = close[i] > open[i]
        if is_green and close[i] > ema_9[i]
            continue
        if ema_9[i] > open[i]
            price_above_ema_for_last_bars := false
            break

    current_timeframe = str.tonumber(timeframe.period)
    trend_started_bar_index = get_trend_started_bar_index(index, vwap, ema_9, vol_avg)
    // if time == timestamp(relevant_timezone, 2025, 7, 23, 13, 55) and timeframe.period == "5"
    //     log.info("trend_started_bar_index: {0}", trend_started_bar_index)

    at_least_one_bar_is_red = false
    strong_green_bars_counter = 1
    weak_green_bars_counter = 0
    green_volatile_bars_counter = 0
    red_volatile_bars_counter = 0
    for i = trend_started_bar_index to index+1
        is_green = close[i] > open[i]
        is_strong = (close[i] - open[i]) > (high[i] - close[i]) or high[i] == close[i]
        if volume[i] > vol_avg[i] * 1.5 and not is_green and trend_started_bar_index/2 > i
            red_volatile_bars_counter += 1
        if is_green
            if not at_least_one_bar_is_red
                at_least_one_bar_is_red := close[i] < high[i] and open[i] > low[i] and (close[i]-open[i]) < (high[i]-close[i]) and (close[i]-open[i]) < (open[i]-low[i])
            if trend_started_bar_index/2 > i
                green_volatile_bars_counter += 1
            if is_strong
                strong_green_bars_counter += 1
            else
                weak_green_bars_counter += 1
        else
            at_least_one_bar_is_red := true

    green_bars_before_are_strong = strong_green_bars_counter/weak_green_bars_counter >= 0.6
     or green_volatile_bars_counter > red_volatile_bars_counter

    ema_change_is_higher = true
    current_ema_change = ema_9[index] - ema_9[index+1]
    for i = trend_started_bar_index-2 to index+1
        if i < 0
            continue
        ema_change = ema_9[i] - ema_9[i+1]
        if ema_change > current_ema_change + 0.01
            // if time == timestamp(relevant_timezone, 2025, 7, 1, 10, 25) and timeframe.period == "5"
            //     log.info("i: {0}", i)
            ema_change_is_higher := false
            break

    no_higher_bar_between_start_to_current = true
    most_volatile_bar_is_not_red = true
    no_really_small_value_bar = true
    most_bars_closed_percentage = 0.0
    most_bars_closed_percentage_counter = 0
    highest_volume = 0.0
    highest_volume_bar_index = 0
    for i = trend_started_bar_index to index
        if volume[i] > highest_volume
            highest_volume := volume[i]
            highest_volume_bar_index := i
        if i < trend_started_bar_index and high[i] > high[index]
            no_higher_bar_between_start_to_current := false

        if close[i] > open[i]
            most_bars_closed_percentage += (close[i] - open[i])/(high[i] - low[i])
            most_bars_closed_percentage_counter += 1

    closed_percentage = most_bars_closed_percentage/most_bars_closed_percentage_counter
    most_bars_closed_strong = closed_percentage >= 0.45

    if close[highest_volume_bar_index] < open[highest_volume_bar_index] and (open[highest_volume_bar_index] - close[highest_volume_bar_index])/(close[highest_volume_bar_index+1]-open[highest_volume_bar_index+1]) >= 0.5
        most_volatile_bar_is_not_red := false

    keeping_support_line = true
    number_of_bars_with_no_mevement_counter = 0
    no_weak_bar_under_all_indications = true
    for i = trend_started_bar_index-1 to index+1
        if trend_started_bar_index-1 < 0 or i-1 < 0
            continue

        if close[i] < open[i] and close[i] < ema_9[i] and close[i] < vwap[i] and close[i] < ema_20[i]
            no_weak_bar_under_all_indications := false
            break

        if math.round(close[i] * 100)/100 == math.round(open[i] * 100)/100
            number_of_bars_with_no_mevement_counter += 1

        bar_is_green = close[i] > open[i]
        bar_after_is_red = close[i-1] < open[i-1]
        its_not_the_pre_market = minute[i] != 30

        if bar_is_green and bar_after_is_red and low[i] > low[i-1] and low[i-1] > ema_9[i-1] + 0.02 and i - index <= 4
            keeping_support_line := false

    current_bar_is_in_volume_trend = current_bar_is_in_volume_trend(index, trend_started_bar_index, vol_avg, vwap)
    number_of_bars_with_no_mevement_is_low = number_of_bars_with_no_mevement_counter <= 2

    most_value_did_not_come_from_start_index = (high[trend_started_bar_index] - low[trend_started_bar_index])/(high[index]-low[trend_started_bar_index]) <= 0.5
    ema_200_day_is_close = high[index]/ema_200_days >= 0.75

    result = volume_has_changed
     and price_has_changed
     and price_above_ema_for_last_bars
     and lows_above_ema
     and bar_before_didnt_do_much
     and bar_before_price_movement_was_low
     and (trend_started_bar_index >= 4 or (hour[trend_started_bar_index] == 9 and minute[trend_started_bar_index] == 30 and trend_started_bar_index >= 1))
     and volume[index]/volume[trend_started_bar_index] > 0.7
     and close[index] > close[trend_started_bar_index] + 0.01
     and green_bars_before_are_strong
     and ema_change_is_higher
     and most_volatile_bar_is_not_red
     and at_least_one_bar_is_red
     and current_bar_closed_strong
     and no_higher_bar_between_start_to_current
     and current_bar_is_in_volume_trend
     and vol_avg[index] >= 8000
     and most_value_did_not_come_from_start_index
     and no_really_small_value_bar
     and open[index] >= 1
     and keeping_support_line
     and most_bars_closed_strong
     and number_of_bars_with_no_mevement_is_low
     and no_weak_bar_under_all_indications
     and volume[index] >= volume[index+1] * 1.5
     and not ema_200_day_is_close

    if result
        log.info("EMA is changing up!. start_index: {0}. strong_odds: {1}", trend_started_bar_index, closed_percentage)
        l = label.new(x=bar_index-1, y=close + 0.5, textcolor = color.yellow, size = size.small, style = label.style_label_right)
        label.set_text(id=l, text=str.format("Start Index: {0}.\nStrong Odds: {1}.", trend_started_bar_index, closed_percentage))

    result

///          Buyers Coming In Indication          ///

_bar_is_strong(index) =>
    there_are_buyers_at_the_bottom = (open[index] - low[index])/(high[index]-low[index]) < 0.5
    bar_closes_with_buyers = (close[index] - open[index])/(high[index]-low[index]) >= 0.5
    bar_higher_than_bar_before = high[index] > high[index+1]
    bar_stronger_than_bar_before = volume[index] > volume[index+1] * 2

    there_are_buyers_at_the_bottom
     and bar_closes_with_buyers
     and bar_higher_than_bar_before
     and bar_stronger_than_bar_before

_ema_change_is_highest_on_current_bar(index, trend_started_bar_index) =>
    bar_ema_9_sum = 0.0
    volume_is_highest = true
    bar_is_weak = false
    no_bar_is_higher = true
    for i = trend_started_bar_index-1 to index
        if i < 0
            continue

        if high[i] > close[index] and i > index
            no_bar_is_higher := false

        bar_ema_9_sum += ema_9[i] - ema_9[i+1]
        if volume[i] > volume[index] or vol_avg[i] > vol_avg[index] or vol_avg[index] > volume[index]
            volume_is_highest := false

        if close[i] < ema_20[i]
            bar_is_weak := true

    bar_ema_9_avg = bar_ema_9_sum/trend_started_bar_index
    bar_ema_change_is_highest = ema_9[index] - ema_9[index+1] > bar_ema_9_avg
    current_bar_closes_to_9_ema = true
    if low[index] > ema_9[index]
        distance_lower_than_half_from_last_bar = true
        if close[index+1] != open[index+1]
            distance_lower_than_half_from_last_bar := low[index] - ema_9[index] < (high[index+1] - low[index+1])/2
        current_bar_closes_to_9_ema := (low[index] - ema_9[index])/ema_9[index] <= 0.05 and distance_lower_than_half_from_last_bar

    bar_ema_change_is_highest
     and not bar_is_weak
     and volume_is_highest
     and no_bar_is_higher
     and current_bar_closes_to_9_ema

_strongest_bar_is_close_to_current_bar(index, trend_started_bar_index) =>
    strongest_bar_index = 0
    strongest_bar_value = 0.0
    for i = trend_started_bar_index to index
        if high[i] - low[i] > strongest_bar_value
            strongest_bar_value := high[i] - low[i]
            strongest_bar_index := i

    strongest_bar_is_close_to_current_bar = strongest_bar_index <= math.round(trend_started_bar_index/2)
    strongest_bar_is_close_to_current_bar

buyers_coming_in_indication(index) =>
    yesterday_close = request.security(syminfo.tickerid, "D", close[1], lookahead = barmerge.lookahead_on)

    bar_is_strong = _bar_is_strong(index)
    trend_started_bar_index = get_trend_started_bar_index(index, vwap, ema_9, vol_avg)
    moved_already_at_least_20_percent_since_yesterday = (close[index] - yesterday_close)/close[index] >= 0.2
    ema_change_is_highest_on_current_bar = _ema_change_is_highest_on_current_bar(index, trend_started_bar_index)
    strongest_bar_is_close_to_current_bar = _strongest_bar_is_close_to_current_bar(index, trend_started_bar_index)

    red_before_is_weak = true
    bar_before_is_red = close[index+1] < open[index+1]
    bar_before_that_is_green = close[index+2] > open[index+2]
    if bar_before_is_red and bar_before_that_is_green
        red_before_is_weak := (open[index+1] - close[index+1])/(close[index+2]-open[index+2]) <= 0.5

    price_is_volatile = high[index] - low[index] > 0.05

    result = bar_is_strong
     and moved_already_at_least_20_percent_since_yesterday
     and trend_started_bar_index >= 4
     and ema_change_is_highest_on_current_bar
     and red_before_is_weak
     and price_is_volatile
    // and strongest_bar_is_close_to_current_bar

    if result
        log.info("Buyers Coming In!. start_index: {0}", trend_started_bar_index)
        l = label.new(x=bar_index-1, y=close + 0.5, textcolor = color.yellow, size = size.small, style = label.style_label_right)
        label.set_text(id=l, text=str.format("s: {0}.", trend_started_bar_index))

    result


///          Indications          ///
bar_is_acting_as_reversal_upwards = bar_is_acting_as_reversal_upwards(0)
bar_ema_is_changing_up = bar_ema_is_changing_up(0)
buyers_coming_in_indication = buyers_coming_in_indication(0)

plotshape(bar_is_acting_as_reversal_upwards, title="Reversal pattern", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = reversal_sign)
plotshape(bar_ema_is_changing_up, title="EMA is changing up", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = "📈")
plotshape(buyers_coming_in_indication, title="Buyers Coming In", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = "🛫")

alertcondition(bar_is_acting_as_reversal_upwards or buyers_coming_in_indication or bar_ema_is_changing_up, title="Positive indication for long/short momentum", message="Positive indication for long/short momentum")
