// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TheFirstPatienceTrader

indicator(title="Continues Trend", overlay = true, max_bars_back = 5000)
import TradingView/ta/10

//@version=6

relevant_timezone = "America/New_York"

ema_9 = ta.ema(close, 9)
vwap = ta.vwap(hlc3)
vol_avg = ta.sma(volume, 20)
[macd, signal_line, histogram] = ta.macd(close, 12, 26, 9)
current_timeframe = str.tonumber(timeframe.period)
if timeframe.period == "10S"
    current_timeframe := 10

bars_back = (((hour[0] - 4) * 60) + minute[0])/current_timeframe

// if time == timestamp(relevant_timezone, 2025, 9, 18, 11, 50) and current_timeframe == 5
//     log.info("some log")

_made_more_than_usual_percentage_already(index, percentage) =>
    yesterday_close = request.security(syminfo.tickerid, "D", close[1], lookahead = barmerge.lookahead_on)
    (close[index] - yesterday_close)/open[index] > percentage

_get_starting_index(index, with_threshold) =>
    starting_index = 0
    min_bars_back = math.min(bars_back, 40)
    for i = index+1 to index+min_bars_back
        if i < 0
            continue
        is_first_bar_to_pop_up = close[i] > open[i]
         and volume[i] > volume[i+1] * 2
         and volume[i] > vol_avg[i]
         and close[i] > ema_9[i]
         and high[i] > vwap[i]
         and high[i] - low[i] > (high[i+1] - low[i+1]) * 2
         and (close[i] - open[i])/(high[i] - low[i]) >= 0.3
         and dayofmonth[i] == dayofmonth[index]
         and high[i] > vwap[i]

        if with_threshold
            is_first_bar_to_pop_up := is_first_bar_to_pop_up
             and volume[i] > 40000

        if is_first_bar_to_pop_up
            for j = i+60 to i+1
                if dayofmonth[j] != dayofmonth[i]
                    continue

                if volume[j] >= volume[i]
                 and high[j] >= high[i]
                    is_first_bar_to_pop_up := false
                    break

                if volume[j]/volume[i] >= 0.75 and j - i < 10 and volume[j] > vol_avg[j] and with_threshold
                    is_first_bar_to_pop_up := false
                    break

                if volume[j]/volume[i] >= 0.6 and (high[j] - low[j])/(high[i] - low[i]) > 0.9
                    is_first_bar_to_pop_up := false
                    break

            if is_first_bar_to_pop_up
                starting_index := i
                break

    starting_index

_get_top_index(index, starting_index) =>
    highest_high = 0.0
    highest_high_index = 0
    for i = index+3 to starting_index
        if high[i] > highest_high
            highest_high := high[i]
            highest_high_index := i

    top_index = 0
    for i = index to starting_index
        if i-1 < 0
            continue

        if high[i] > high[i+1]
         and high[i] > high[i-1]
         and close[i] > ema_9[i]
         and volume[i] > vol_avg[i]
         and high[i] == highest_high
            top_index := i
            break


    top_index

_get_lowest_point_from_top_point_index(index, top_index) =>
    lowest_point_from_top_point_value = 1000.0
    lowest_point_from_top_point_index = 0
    for i = index+1 to top_index-1
        if i < 0
            continue
        if low[i] < lowest_point_from_top_point_value
            lowest_point_from_top_point_value := low[i]
            lowest_point_from_top_point_index := i

    lowest_point_from_top_point_index

_move_is_still_strong_due_to_fibonacci_retracement(index, starting_index, top_index, lowest_point_from_top_point_index) =>
    fibonacci_retracement = (high[top_index] - low[lowest_point_from_top_point_index])/(high[top_index] - open[starting_index])
    move_is_still_strong_due_to_fibonacci_retracement = starting_index > top_index
     and fibonacci_retracement <= 0.62
     and fibonacci_retracement >= 0.3

    if not move_is_still_strong_due_to_fibonacci_retracement and top_index-1 > 0
        move_is_still_strong_due_to_fibonacci_retracement := close[index] > high[top_index-1]
         and fibonacci_retracement <= 0.8
         and fibonacci_retracement >= 0.3

    [move_is_still_strong_due_to_fibonacci_retracement, fibonacci_retracement]

_current_bar_should_be_involved_with_9_ema(index, top_index) =>
    distance_from_ema_9 = math.abs(ema_9[index] - open[index])/(high[index] - open[index])

    open_under_ema_9_but_bar_is_strong = true
     and open[index] <= ema_9[index]
     and math.abs(ema_9[index] - low[index])/(high[index] - low[index]) <= 0.10

    open_above_ema_9_but_close = true
     and open[index] > ema_9[index]
     and (low[index] - ema_9[index])/(high[index] - low[index]) <= 0.10

    ema_9_change_is_higher_than_before = true
     and ema_9[index] - ema_9[index+1] > ema_9[index+1] - ema_9[index+2]

    ema_9_change_from_top_index_is_highest = true
    current_change = ema_9[index] - ema_9[index+1]
    for i = top_index-1 to index+1
        if i < 0
            continue
        if ema_9[i] - ema_9[i+1] >= current_change
            ema_9_change_from_top_index_is_highest := false

    not_close_but_strong = ema_9_change_from_top_index_is_highest
     and histogram[index] > histogram[index+1]
     and histogram[index+2] > histogram[index+1]
     and histogram[index+3] > histogram[index+2]

    ema_9_change_is_higher_than_before
     and (open_under_ema_9_but_bar_is_strong or open_above_ema_9_but_close or not_close_but_strong)

_milestones_are_valid(index, starting_index, top_index) =>
    milestones_are_valid = true
     and starting_index != top_index
     and starting_index > index
     and top_index > index
     and starting_index > 0
     and top_index > 0

_histogram_looks_good(index, top_index) =>
    histogram_changed_direction = histogram[index] > histogram[index+1]
     and histogram[index+1] < histogram[index+2]

    histogram_raised_significantly = true
     and histogram[index+2] < histogram[index+1]
     and histogram[index+1] < histogram[index]
     and histogram[index+2]/histogram[index+1] >= 0.85
     and histogram[index] - histogram[index+1] > (histogram[index+1] - histogram[index+2]) * 2

    histogram_changed_significantly = histogram_changed_direction
     or histogram_raised_significantly

    histogram_changed_significantly
     and histogram[index]/histogram[top_index] >= 0.5

_current_bar_close_close_to_high(index) =>
    close[index]/high[index] >= 0.7

_most_of_current_body_is_above_9_ema(index) =>
    most_of_current_body_is_above_9_ema = open[index] >= ema_9[index]
    if not most_of_current_body_is_above_9_ema
        most_of_current_body_is_above_9_ema := (ema_9[index] - open[index])/(high[index] - open[index]) <= 0.2

    most_of_current_body_is_above_9_ema
     and ema_9[index]/low[index] > 0.95

_current_volume_is_strong_with_high_volume(index, top_index) =>
    current_volume_is_strong_with_high_volume = true
     and close[index] > open[index]
     and low[index]/open[index] > 0.98
     and (close[index] - open[index])/(high[index] - low[index]) >= 0.6

    for i = top_index-1 to index
        if i < 0
            continue

        if volume[index]/volume[i] < 0.8
            current_volume_is_strong_with_high_volume := false
            break

    current_volume_is_strong_with_high_volume

_most_of_bars_are_volatile(starting_index, index) =>
    volatile_bars = 0
    for i = starting_index to index
        if volume[i] >= 40000
            volatile_bars += 1

    most_of_bars_are_volatile = volatile_bars/starting_index >= 0.6

    most_of_bars_are_volatile

_histogram_is_positive_until_now(starting_index, index) =>
    histogram_is_positive_until_now = true
    for i = starting_index to index
        if histogram[i] < 0
            histogram_is_positive_until_now := false
            break

    top_histogram_index = 0
    top_histogram_value = 0.0
    for i = starting_index to index+1
        if histogram[i] > top_histogram_value
            top_histogram_value := histogram[i]
            top_histogram_index := i

    histogram_top_appears_count = 0
    for i = top_histogram_index to index+1
        if i-1 < 0
            continue

        if histogram[i] > histogram[i-1]
         and histogram[i] > histogram[i+1]
         and i > index
         and i < top_histogram_index
            histogram_top_appears_count += 1

    histogram_changed_direction = histogram[index] > histogram[index+1]
     and histogram[index+1] < histogram[index+2]
     and histogram_top_appears_count < 2

    [histogram_is_positive_until_now
     and histogram_changed_direction, top_histogram_index]

_negative_bars_volume_is_going_down(starting_index, index) =>
    negative_bars_volume_is_going_down = true
    for i = starting_index-1 to index
        if i < 0
            continue
        if close[i] < open[i]
         and close[i+1] < open[i+1]
         and volume[i] >= volume[i+1]
            negative_bars_volume_is_going_down := false
            break

    negative_bars_volume_is_going_down

_negative_bars_are_weak(top_index, index) =>
    negative_bars_are_weak = true
    for i = top_index-1 to index
        if i < 0
            continue

        if close[i] < open[i]
         and close[i+1] > open[i+1]
         and volume[i] > volume[i+1]
         and volume[i] > vol_avg[i]
            negative_bars_are_weak := false
            break

        if close[i] < open[i]
         and volume[i] > vol_avg[i]
         and low[i]/close[i] > 0.95
         and (high[i] - open[i])/(high[i] - low[i]) >= 0.4
            negative_bars_are_weak := false

    negative_bars_are_weak

_retracement_should_be_long_enough(index, top_index) =>
    base_condition = top_index >= 3
    retracement_should_be_long_enough = true
    for i = top_index to index+1
        if close[i] > open[i]
            retracement_should_be_long_enough := false
            break

    retracement_should_be_long_enough or base_condition

_starting_index_is_not_the_biggest_bar(index, starting_index) =>
    starting_index_is_not_the_biggest_bar = false
    for i = starting_index-1 to index
        if i < 0
            continue

        if volume[i] >= volume[starting_index]
            starting_index_is_not_the_biggest_bar := true
            break

    starting_index_is_not_the_biggest_bar

_volume_sum_is_positive(index, starting_index, positive_volume_bigger_by_percentage) =>
    positive_volume_sum = 0.0
    negative_volume_sum = 0.0

    for i = starting_index to index
        if close[i] > open[i]
            positive_volume_sum += volume[i]
        else
            negative_volume_sum += volume[i]

    result = positive_volume_sum > negative_volume_sum
    if positive_volume_bigger_by_percentage > 0.0
        result := negative_volume_sum/positive_volume_sum < positive_volume_bigger_by_percentage

    result

_current_bar_crossed_finally_highest_high(index, top_index, starting_index) =>
    current_bar_crossed_finally_highest_high = close[index] > high[top_index]
    attempts_indexes = array.new_int()

    for i = starting_index to index+1
        if high[i]/high[top_index] >= 0.96
         and (close[i] - low[i])/(high[i] - low[i]) <= 0.7
            array.push(attempts_indexes, i)

    current_bar_crossed_finally_highest_high := true
     and current_bar_crossed_finally_highest_high
     and array.size(attempts_indexes) >= 2

    [current_bar_crossed_finally_highest_high, attempts_indexes]

_no_more_than_2_retracements_until_now(index, starting_index) =>
    retracements_indexes = array.new_int()
    for i = starting_index to index
        if i-1 < 0
            continue

        retracement_case_1 = true
         and high[i] < high[i+1]
         and high[i] < high[i-1]
         and close[i-1] > open[i-1]
         and (low[i] <= ema_9[i] or ema_9[i]/low[i] >= 0.9)

        retracement_case_2 = true
         and high[i] < high[i+1]
         and low[i] < low[i+1]
         and low[i] < low[i-1]
         and close[i-1] > open[i-1]
         and (low[i] <= ema_9[i] or ema_9[i]/low[i] >= 0.9)

        result = retracement_case_1
         or retracement_case_2

        if i > 2
            result := (retracement_case_1 or retracement_case_2) and (high[i-1] < high[i-2] or low[i-1] < low[i-2])

        if result
            if not array.includes(retracements_indexes, i+1)
                array.push(retracements_indexes, i)

    retracements_count = array.size(retracements_indexes)

    [retracements_count <= 2 and retracements_count >= 1, retracements_indexes]

_current_bar_high_close_to_top_high(index, top_index, starting_index) =>
    base_condition = high[index]/high[top_index] >= 0.99
    current_bar_high_close_to_top_high = true
    for i = starting_index to index+1
        if close[i] > close[index]
            current_bar_high_close_to_top_high := false
            break

    current_bar_high_close_to_top_high or base_condition

_most_of_volume_are_stuck_between_top_index_to_current(index, top_index, starting_index) =>
    all_volume_from_movement = 0.0
    for i = starting_index to index
        all_volume_from_movement += volume[i]

    volume_from_top_index = 0.0
    for i = top_index to index
        volume_from_top_index += volume[i]

    volume_percentage_from_top = volume_from_top_index/all_volume_from_movement
    bars_percentage_from_top = top_index/starting_index

    most_of_volume_are_stuck_between_top_index_to_current = bars_percentage_from_top/volume_percentage_from_top < 0.9

    [most_of_volume_are_stuck_between_top_index_to_current, volume_percentage_from_top, bars_percentage_from_top]

_histogram_has_at_least_2_weak_bars_from_top(index) =>
    histogram_has_at_least_2_weak_bars_from_top = true
     and histogram[index+1] < histogram[index+2]
     and histogram[index+2] < histogram[index+3]

_current_bar_is_halted(index) =>
    current_bar_is_halted = true
     and close[index] == high[index]
     and close[index] - open[index] > (close[index+1] - open[index+1]) * 2
     and high[index] - high[index+1] > 0.4
     and close[index] > vwap[index]
     and close[index] > ema_9[index]
     and histogram[index] > 0
     and volume[index] > 5000

_current_bar_is_highest_for_halted(index, starting_index, top_index) =>
    current_bar_is_highest_for_halted = true
    for i = starting_index to index+1
        if high[i] > high[index]
            current_bar_is_highest_for_halted := false
            break

    milestones_are_valid = _milestones_are_valid(index, starting_index, top_index)

    current_bar_is_highest_for_halted and milestones_are_valid

///////////// Indications /////////////
base_case_check(index) =>
    starting_index = _get_starting_index(index, true)
    top_index = _get_top_index(index, starting_index)

    percentage = 0.1
    made_more_than_usual_percentage_already = _made_more_than_usual_percentage_already(index, percentage)
    movement_is_after_market_start = hour[index] >= 9 and hour[index] <= 20
    current_bar_close_close_to_high = _current_bar_close_close_to_high(index)
    current_bar_high_close_to_top_high = _current_bar_high_close_to_top_high(index, top_index, starting_index)
    milestones_are_valid = _milestones_are_valid(index, starting_index, top_index)
    lowest_point_from_top_point_index = _get_lowest_point_from_top_point_index(index, top_index)
    [move_is_still_strong_due_to_fibonacci_retracement, fibonacci_retracement] = _move_is_still_strong_due_to_fibonacci_retracement(index, starting_index, top_index, lowest_point_from_top_point_index)
    current_volume_is_strong_with_high_volume = _current_volume_is_strong_with_high_volume(index, top_index)
    most_of_bars_are_volatile = _most_of_bars_are_volatile(starting_index, index)
    [histogram_is_positive_until_now, top_histogram_index] = _histogram_is_positive_until_now(starting_index, index)
    [no_more_than_2_retracements_until_now, retracements_indexes] = _no_more_than_2_retracements_until_now(index, starting_index)
    retracement_should_be_long_enough = _retracement_should_be_long_enough(index, top_index)
    [most_of_volume_are_stuck_between_top_index_to_current, volume_percentage_from_top, bars_percentage_from_top] = _most_of_volume_are_stuck_between_top_index_to_current(index, top_index, starting_index)
    histogram_has_at_least_2_weak_bars_from_top = _histogram_has_at_least_2_weak_bars_from_top(index)

    base_indication = true
     and made_more_than_usual_percentage_already
     and movement_is_after_market_start
     and current_bar_close_close_to_high
     and milestones_are_valid
     and move_is_still_strong_due_to_fibonacci_retracement
     and most_of_bars_are_volatile
     and histogram_is_positive_until_now
     and no_more_than_2_retracements_until_now
     and current_bar_high_close_to_top_high
     and retracement_should_be_long_enough
     and not most_of_volume_are_stuck_between_top_index_to_current
     and histogram_has_at_least_2_weak_bars_from_top

    [base_indication, starting_index, top_index, lowest_point_from_top_point_index, top_histogram_index, fibonacci_retracement, retracements_indexes, volume_percentage_from_top, bars_percentage_from_top]

cases(index) =>
    main_case = false
    [base_indication, starting_index, top_index, lowest_point_from_top_point_index, top_histogram_index, fibonacci_retracement, retracements_indexes, volume_percentage_from_top, bars_percentage_from_top] = base_case_check(index)
    negative_bars_are_weak = _negative_bars_are_weak(top_index, index)
    most_of_current_body_is_above_9_ema = _most_of_current_body_is_above_9_ema(index)
    current_volume_is_strong_with_high_volume = _current_volume_is_strong_with_high_volume(index, top_index)
    starting_index_is_not_the_biggest_bar = _starting_index_is_not_the_biggest_bar(index, starting_index)
    negative_bars_volume_is_going_down = _negative_bars_volume_is_going_down(starting_index, index)
    [current_bar_crossed_finally_highest_high, attempts_indexes] = _current_bar_crossed_finally_highest_high(index, top_index, starting_index)
    volume_sum_is_positive = _volume_sum_is_positive(index, starting_index, 0.0)

    case_1 = true
     and base_indication
     and volume_sum_is_positive
     and negative_bars_are_weak
     and most_of_current_body_is_above_9_ema
     and current_volume_is_strong_with_high_volume
     and negative_bars_volume_is_going_down

    if case_1
        log.info("case 1. starting_index: {0}. top_index: {1}.", starting_index, top_index)
        main_case := case_1

    case_2 = true
     and base_indication
     and volume_sum_is_positive
     and most_of_current_body_is_above_9_ema
     and current_volume_is_strong_with_high_volume
     and negative_bars_volume_is_going_down

    if case_2
        log.info("case 2. starting_index: {0}. top_index: {1}.", starting_index, top_index)
        main_case := case_2

    case_3 = true
     and base_indication
     and volume_sum_is_positive
     and starting_index_is_not_the_biggest_bar
     and negative_bars_volume_is_going_down
     and fibonacci_retracement > 0.4
     and fibonacci_retracement < 0.5

    if case_3
        log.info("case 3. starting_index: {0}. top_index: {1}.", starting_index, top_index)
        main_case := case_3

    case_4 = true
     and base_indication
     and volume_sum_is_positive
     and starting_index_is_not_the_biggest_bar
     and current_bar_crossed_finally_highest_high
     and fibonacci_retracement > 0.4
     and fibonacci_retracement < 0.5

    if case_4
        log.info("case 4. starting_index: {0}. top_index: {1}.", starting_index, top_index)
        main_case := case_4

    _volume_sum_is_positive = _volume_sum_is_positive(index, starting_index, 0.5)
    case_5 = true
     and base_indication
     and _volume_sum_is_positive
     and starting_index_is_not_the_biggest_bar
     and negative_bars_volume_is_going_down
     and fibonacci_retracement > 0.3
     and fibonacci_retracement < 0.5
     and starting_index >= 8

    if case_5
        log.info("case 5. starting_index: {0}. top_index: {1}.", starting_index, top_index)
        main_case := case_5

    case_6 = true
     and base_indication
     and _volume_sum_is_positive
     and starting_index_is_not_the_biggest_bar
     and fibonacci_retracement > 0.5
     and fibonacci_retracement < 0.72
     and array.size(retracements_indexes) == 1

    if case_6
        log.info("case 6. starting_index: {0}. top_index: {1}.", starting_index, top_index)
        main_case := case_6

    ////////////       HALTED CASE       //////////// --- variables new initialization!
    _starting_index = _get_starting_index(index, false)
    _top_index = _get_top_index(index, _starting_index)
    retracement_should_be_long_enough = _retracement_should_be_long_enough(index, _top_index)
    made_more_than_usual_percentage_already = _made_more_than_usual_percentage_already(index, 0.1)
    movement_is_after_market_start = hour[index] >= 9 and hour[index] <= 20
    _lowest_point_from_top_point_index = _get_lowest_point_from_top_point_index(index, top_index)
    [_move_is_still_strong_due_to_fibonacci_retracement, _fibonacci_retracement] = _move_is_still_strong_due_to_fibonacci_retracement(index, _starting_index, _top_index, _lowest_point_from_top_point_index)
    negative_bars_are_weak := _negative_bars_are_weak(_top_index, index)
    most_of_current_body_is_above_9_ema := _most_of_current_body_is_above_9_ema(index)
    current_bar_is_halted = _current_bar_is_halted(index)
    current_bar_is_highest_for_halted = _current_bar_is_highest_for_halted(index, starting_index, top_index)

    halted_case = true
     and made_more_than_usual_percentage_already
     and movement_is_after_market_start
     and (_move_is_still_strong_due_to_fibonacci_retracement or current_bar_is_highest_for_halted)
     and most_of_current_body_is_above_9_ema
     and retracement_should_be_long_enough
     and current_bar_is_halted

    if halted_case
        starting_index := _starting_index
        top_index := _top_index
        fibonacci_retracement := _fibonacci_retracement
        lowest_point_from_top_point_index := _lowest_point_from_top_point_index

        log.info("HALTED SYMBOL! halted case. starting_index: {0}. top_index: {1}.", starting_index, top_index)
        main_case := halted_case

    [main_case, fibonacci_retracement, starting_index, top_index, top_histogram_index, lowest_point_from_top_point_index, attempts_indexes, retracements_indexes, volume_percentage_from_top, bars_percentage_from_top]

[main_case, fibonacci_retracement, starting_index, top_index, top_histogram_index, lowest_point_from_top_point_index, attempts_indexes, retracements_indexes, volume_percentage_from_top, bars_percentage_from_top] = cases(0)
if main_case
    confirmation_label = label.new(bar_index, high, text = "✅", size = size.tiny)
    label.set_tooltip(confirmation_label, str.format("starting_index: {0}. top_index: {1}. fibonacci_retracement: {2}. lowest_point_from_top_point_index: {3}. top_histogram_index: {4}. attempts_indexes: {5}. retracements_indexes: {6}. volume_percentage_from_top: {7}. bars_percentage_from_top: {8}", starting_index, top_index, fibonacci_retracement, lowest_point_from_top_point_index, top_histogram_index, attempts_indexes, retracements_indexes, volume_percentage_from_top, bars_percentage_from_top))

plotshape(main_case, title="case 1", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.belowbar, text = "💰")

plot(fibonacci_retracement, "fibonacci_retracement", display = display.status_line)
plot(starting_index, "starting_index", display = display.status_line)
plot(top_index, "top_index", display = display.status_line)

alertcondition(main_case, title="Positive indication for long/short momentum", message="Positive indication for long/short momentum")
