// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TheFirstPatienceTrader

indicator(title="Moving up", overlay = true, max_bars_back = 5000)
import TradingView/ta/10

//@version=6

relevant_timezone = "America/New_York"

ema_9 = ta.ema(close, 9)
ema_20 = ta.ema(close, 20)
vwap = ta.vwap(hlc3)
vol_avg = ta.sma(volume, 20)
[macd, signal_line, histogram] = ta.macd(close, 12, 26, 9)
current_timeframe = str.tonumber(timeframe.period)
if timeframe.period == "10S"
    current_timeframe := 10

_made_more_than_usual_percentage_already(index, percentage) =>
    yesterday_close = request.security(syminfo.tickerid, "D", close[1], lookahead = barmerge.lookahead_on)
    if (hour[index] == 9 and minute[index] < 30) or hour[index] < 9
        yesterday_close := request.security(syminfo.tickerid, "D", close, lookahead = barmerge.lookahead_on)
    (close[index] - yesterday_close)/open[index] > percentage

_current_bar_volume_is_moving_up_for_real(index) =>
    bars_back = 10
    last_bars_volume_sum = 0.0
    for i = bars_back+index to index+1
        last_bars_volume_sum += volume[i]

    volume_threshold = 1000000
    last_bars_volume_is_high = last_bars_volume_sum > volume_threshold

    current_volume_is_much_higher = true
     and volume[index] > 1000000
     and volume[index] > vol_avg[index]
     and volume[index] > volume[index+1] * 3

    current_price_movement_is_much_higher = true
     and high[index] - low[index] > (high[index+1] - low[index+1]) * 2
     and (close[index+1] - open[index])/(close[index] - open[index]) < 0.3

    current_volume_is_higher_than_last_bars = true
    current_high_is_higher_than_last_bars = true
    for i = index+5 to index+1
        if volume[i] > volume[index]
            current_volume_is_higher_than_last_bars := false

        if high[i] > high[index]
            current_high_is_higher_than_last_bars := false

    current_bars_volume_sum = 0.0
    previous_bars_volume_sum = 0.0

    for i = index+20 to index+11
        previous_bars_volume_sum += volume[i]

    for i = index+10 to index+1
        current_bars_volume_sum += volume[i]

    volume_is_the_last_bars_is_higher_than_before = current_bars_volume_sum > previous_bars_volume_sum

    at_least_one_bar_before_above_vwap = false
    for i = index+10 to index+1
        if close[i] > vwap[i]
            at_least_one_bar_before_above_vwap := true
            break

    basic_scenario = true
     and last_bars_volume_is_high
     and current_volume_is_much_higher
     and current_price_movement_is_much_higher
     and current_volume_is_higher_than_last_bars
     and current_high_is_higher_than_last_bars
     and at_least_one_bar_before_above_vwap

    current_bar_is_right_after_market_starts_to_move = (hour[index] == 9 and minute[index] > 30) or (hour[index] > 9 and hour[index] < 11)
    bar_closing_high = (high[index] - close[index])/(high[index] - low[index]) < 0.3
    volume_is_strong = true
     and volume[index] > vol_avg[index]
     and volume[index] > volume[index+1]
     and volume[index] > 100000

    specific_scenario = true
     and current_price_movement_is_much_higher
     and current_high_is_higher_than_last_bars
     and current_bar_is_right_after_market_starts_to_move
     and bar_closing_high
     and volume_is_strong
     and at_least_one_bar_before_above_vwap

    true
     and (basic_scenario or specific_scenario)

_bar_is_positive(index) =>
    bar_is_positive = close[index] > open[index]
    bar_above_all_indicators = true
     and high[index] > ema_9[index]
     and high[index] > vwap[index]

    true
     and bar_is_positive
     and bar_above_all_indicators

moving_up_indication(index) =>
    percentage = 0.1
    made_more_than_usual_percentage_already = _made_more_than_usual_percentage_already(index, percentage)
    current_bar_volume_is_moving_up_for_real = _current_bar_volume_is_moving_up_for_real(index)
    bar_is_positive = _bar_is_positive(index)
    movement_is_after_market_start = (hour[index] == 9 and minute[index] > 30) or hour[index] > 9

    result = true
     and made_more_than_usual_percentage_already
     and current_bar_volume_is_moving_up_for_real
     and bar_is_positive
     and movement_is_after_market_start

    if result
        log.info("Moving up!")

    result

moving_up_indication = moving_up_indication(0)

plotshape(moving_up_indication, title="Moving up", color=color.green, display = display.pane, style = shape.labeldown, size = size.small, location = location.abovebar, text = "🆙")

alertcondition(moving_up_indication, title="Moving up", message="Moving up")
