// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © amiryaffe

//@version=6
indicator(title="Momentum Indicator for Day Trading", overlay = true)
import TradingView/ta/10


relevant_timezone = "America/New_York"


////           9 EMA Support Indication           ////
ema_support_indication_sign = "🛫👆"

ema_support_indication(index) =>
    [macdLine, signalLine, histogram] = ta.macd(close, 12, 26, 9)
    vol_avg = ta.sma(volume, 20)
    ema_9 = ta.ema(close, 9)
    vwap = ta.vwap(hlc3)

    current_bar_is_highest = true
    ema_was_crossed_down = false
    for i = index+6 to index+1
        if high[i] > close[index]
            current_bar_is_highest := false
        if close[i] < ema_9[i]
            ema_was_crossed_down := true

    bars_prices_are_similar_counter = 0
    for i = index+6 to index+1
        current_close_inside_previus_range = close[i] <= high[i+1] and close[i] >= low[i+1]
        if current_close_inside_previus_range
            bars_prices_are_similar_counter += 1

    bars_price_range_is_different = bars_prices_are_similar_counter <= 4

    last_highest_value = 0.0
    last_highest_index = 0
    for i = index+5 to index+2
        if high[i] > last_highest_value
            last_highest_value := high[i]
            last_highest_index := i

    at_least_one_bar_is_red = false
    for i = last_highest_index+1 to index
        if close[i] < open[i]
            at_least_one_bar_is_red := true
            break

    lowest_price_in_last_bars = ta.lowest(low, 20)
    highest_price_in_last_bars = ta.highest(close, 20)
    current_bar_continues_up_trend = (highest_price_in_last_bars-lowest_price_in_last_bars) / close[index] >= 0.15
    // if time == timestamp(relevant_timezone, year, 6, 25, 9, 49) and timeframe.period == "1"
    //     log.info("l: {0}. h: {1}. r: {2}. p: {3}", lowest_price_in_last_bars, highest_price_in_last_bars, highest_price_in_last_bars-lowest_price_in_last_bars, (highest_price_in_last_bars-lowest_price_in_last_bars) / close[index])

    above_vwap = close[index] > vwap[index] and close[index+1] > vwap[index+1]
    macd_is_positive = macdLine[index] > 0 and histogram[index] > 0 and histogram[index] > histogram[index+1]
    previous_bar_is_strong = close[index+1] > close[index+2] and close[index+1] > open[index+2] and close[index+1] > open[index+1]
    buyers_coming_in = previous_bar_is_strong and volume[index] > (volume[index+1] * 2) and volume[index] > vol_avg[index] and vol_avg[index] > 100000 and vol_avg[index+1] >= 50000 and (close[index] - open[index]) > (high[index] - close[index]) and (high[index] - low[index])/(close[index+1] - open[index+1]) >= 0.9
    bar_full_body_is_strong_than_candles = (open[index]-low[index])/(close[index]-open[index]) <= 0.33
    bar_is_positive = bar_full_body_is_strong_than_candles and close[index] > open[index] and high[index] > high[index+1] and open[index] > open[index+1]
    ema_is_supporting = math.abs(ema_9[index+1] - low[index+1])/(close[index]-low[index]) <= 0.2 and not ema_was_crossed_down

    ema_support_indication = macd_is_positive
     and above_vwap
     and buyers_coming_in
     and bar_is_positive
     and ema_is_supporting
     and current_bar_is_highest
     and current_bar_continues_up_trend
     and bars_price_range_is_different
     and at_least_one_bar_is_red

    ema_support_indication

ema_support_indication = ema_support_indication(0)

// if ema_support_indication and hour >= 6 and hour < 15
//     log.info("Ema Support Indication!")

plotshape(hour >= 4 and hour < 15 ? ema_support_indication : false, title="EMA Support Indication", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.belowbar, text = ema_support_indication_sign)



////           Continues Trend Indication           ////
continues_trend_sign_3_pattern = "🛫3️⃣"
continues_trend_sign_4_pattern = "🛫4️⃣"

previous_positive_bar_is_strong(index, current_index, min_volume_threshold, vol_avg, vwap, ema_9) =>
    bar_is_positive = close[index] > open[index] and high[index] > high[index+1] and close[index] > close[index+1]
    volume_is_strong = (volume[index] > min_volume_threshold and volume[index] > vol_avg[index]) or (volume[index+1] > min_volume_threshold and volume[index+1] > vol_avg[index+1])
    bar_closes_near_to_high = (close[index] - low[index]) >= (high[index] - close[index]) * 1.2 and high[index] - open[index] > open[index] - low[index]
    current_bar_is_volatile = false
    if open[index] > 1
        current_bar_is_volatile := high[index] - open[index] >= 0.15 and high[current_index] - open[current_index] >= 0.15
    else
        current_bar_is_volatile := high[index] - open[index] >= 0.05

    previous_bar_is_strong = bar_is_positive
     and volume_is_strong
     and bar_closes_near_to_high
     and current_bar_is_volatile
     and low[index-1] > vwap[index-1] and (close[index-1]-low[index-1]) / (close[index] - low[index]) < 0.7

    previous_bar_is_strong

current_bar_ema_9_is_above_all(index, vwap) =>
    ema_9 = ta.ema(close, 9)
    ema_20 = ta.ema(close, 20)

    ema_20_is_strong = (ema_20[index] > vwap[index] or ema_20[index]/vwap[index] >= 0.85)
    ema_9[index] > ema_20[index] and ema_9[index] > vwap[index] and ema_20_is_strong

histogram_looks_good(index, histogram, pattern_size, vol_avg) =>
    bar_is_strong = close[index] > open[index] and (close[index] - open[index]) > (open[index] - low[index]) and (close[index] - open[index]) > (high[index] - close[index])
    histogram_looks_good = false
    if pattern_size == 3
        histogram_looks_good := histogram[index] > 0.01 and histogram[index+1] < histogram[index] and histogram[index+1] < histogram[index+2]
        if not histogram_looks_good
            histogram_looks_good := histogram[index] > 0.01 and (histogram[index+1] - histogram[index+2]) * 2 < (histogram[index] - histogram[index+1]) and histogram[index] > histogram[index+1] and bar_is_strong
    else
        histogram_looks_good := histogram[index] > 0.01 and histogram[index+1] < histogram[index] and histogram[index+2] < histogram[index+3]
        if not histogram_looks_good
            histogram_looks_good := histogram[index] > 0.01 and histogram[index+1] < histogram[index] and histogram[index+2]/histogram[index+1] >= 0.95 and bar_is_strong


    histogram_is_not_so_low = true
    for i = index+10 to index
        if histogram[index]/histogram[i] < 0.4 and histogram[i] > 0
            histogram_is_not_so_low := false
            break

    histogram_looks_good and histogram_is_not_so_low and volume[index] > vol_avg[index]

current_bar_is_strong_bar(index, bars_count_pattern) =>
    min_volume_threshold_for_first_strong_bar = 30000
    vol_avg = ta.sma(volume, 20)
    ema_9 = ta.ema(close, 9)
    vwap = ta.vwap(hlc3)
    [macdLine, signalLine, histogram] = ta.macd(close, 12, 26, 9)
    previous_positive_bar_is_strong = false

    pattern_occurred = false
    if bars_count_pattern == 3
        lows_above_vwap = open[index+2] > vwap[index+2] and open[index+1] > vwap[index+1] and low[index] > vwap[index]
        highs_above_vwap = high[index+2] > vwap[index+2] and high[index+1] > vwap[index+1] and high[index] > vwap[index]
        previous_positive_bar_is_strong := previous_positive_bar_is_strong(index+2, index, min_volume_threshold_for_first_strong_bar, vol_avg, vwap, ema_9)
        previous_positive_bar_is_stronger_than_before = (high[index+2]-open[index+2]) > (high[index+3]-open[index+3]) and (high[index+2]-open[index+2]) > (high[index+4]-open[index+4]) and (histogram[index+2]/histogram[index+3] >= 0.75 or histogram[index+2] > histogram[index+3]) and (histogram[index]/histogram[index+2] >= 0.8 or histogram[index] > histogram[index+2])
        previous_positive_bar_is_stronger_than_before_check_number_2 = true
        for i = index+8 to index+3
            if volume[i]/volume[index+2] >= 0.75
                previous_positive_bar_is_stronger_than_before_check_number_2 := false
                break

        no_under_ema_bars_before = true
        for i = index+5 to index
            if close[i] < ema_9[i] and str.tonumber(timeframe.period) == 1
                no_under_ema_bars_before := false
                break

        previous_negative_bar_is_weak = open[index+1] > close[index+1] and volume[index+1] < volume[index+2] and low[index+1] > low[index+2]
        if str.tonumber(timeframe.period) <= 2
            previous_negative_bar_is_weak := previous_negative_bar_is_weak and volume[index+1]/volume[index+2] <= 0.8
        current_bar_is_positive_and_strong = close[index] > open[index] and high[index] > high[index+1] and (volume[index] >= vol_avg[index] * 2 or volume[index] >= min_volume_threshold_for_first_strong_bar)

        pattern_occurred := lows_above_vwap
         and highs_above_vwap
         and previous_negative_bar_is_weak
         and current_bar_is_positive_and_strong
         and (previous_positive_bar_is_stronger_than_before or previous_positive_bar_is_stronger_than_before_check_number_2)
         and no_under_ema_bars_before
    else
        previous_positive_bar_is_strong := previous_positive_bar_is_strong(index+3, index, min_volume_threshold_for_first_strong_bar, vol_avg, vwap, ema_9)
        four_pattern_lows_above_vwap = open[index+3] > vwap[index+3] and open[index+2] > vwap[index+2] and open[index+1] > vwap[index+1] and low[index] > vwap[index]
        four_pattern_previous_positive_bar_is_stronger_than_before = high[index+3] > high[index+4] and high[index+3] > high[index+5] and ((volume[index+3] > volume[index+4] and open[index+4] > close[index+4]) or open[index+4] < close[index+4]) and (histogram[index+3]/histogram[index+4] >= 0.75 or histogram[index+3] > histogram[index+4]) and (histogram[index]/histogram[index+3] >= 0.8 or histogram[index] > histogram[index+3])
        four_pattern_previous_negative_bar_is_weak = open[index+2] > close[index+2] and volume[index+2] < volume[index+3] and low[index+2] > low[index+3]
        four_pattern_third_bar_is_stronger = (close[index+1] > open[index+1] and close[index+1] - open[index+1] > 0.1 and volume[index+1]/volume[index] <= 0.6 and (close[index]-open[index]) > (close[index+1]-open[index+1])) or (open[index+1] > close[index+1] and volume[index+1] < volume[index+2])
        four_pattern_current_bar_is_positive_and_strong = close[index] > open[index] and high[index] > high[index+1]
        four_pattern_weak_bar_before_is_really_weak = low[index+1] < low[index+2] and low[index+1] < low[index+3] and volume[index+1] > vol_avg[index+1]

        previous_positive_bar_is_stronger_than_before = true
        for i = index+9 to index+4
            if volume[i]/volume[index+3] >= 0.75
                previous_positive_bar_is_stronger_than_before := false
                break

        pattern_occurred := four_pattern_lows_above_vwap
         and four_pattern_previous_negative_bar_is_weak
         and four_pattern_current_bar_is_positive_and_strong
         and four_pattern_third_bar_is_stronger
         and (four_pattern_previous_positive_bar_is_stronger_than_before or previous_positive_bar_is_stronger_than_before)
         and not four_pattern_weak_bar_before_is_really_weak

    macd_is_positive = macdLine[index] > 0 and signalLine[index] > 0 and histogram[index] > 0
    current_bar_is_mostly_above_previous_one = (high[index+1] - low[index]) / (high[index] - low[index]) <= 0.5

    volume_is_high_in_the_last_bars = true
    for i = index+5 to index
        if volume[i] < 2000
            volume_is_high_in_the_last_bars := false
            break

    highest_in_the_last_bars = 0.0
    for i = 30 to index+1
        if high[index+i] > highest_in_the_last_bars
            highest_in_the_last_bars := high[index+i]

    current_bar_is_highest_in_the_last_bars = high[index] > highest_in_the_last_bars
    current_bar_ema_9_is_above_all = current_bar_ema_9_is_above_all(index, vwap)
    current_high_is_higher = true
    highest_bar_index = 0
    for i = index+10 to index+1
        if high[i] > high[index]
            current_high_is_higher := false

    current_bar_is_weaker = false
    bars_back = 10
    if str.tonumber(timeframe.period) >= 5
        bars_back := 5
    for i = bars_back to 1
        if high[i] - low[i] > high[index] - low[index] and open[i] > close[i] and volume[i] > volume[index]
            current_bar_is_weaker := true

    current_high_is_higher
     and not current_bar_is_weaker
     and macd_is_positive
     and current_bar_is_mostly_above_previous_one
     and current_bar_is_highest_in_the_last_bars
     and previous_positive_bar_is_strong
     and current_bar_ema_9_is_above_all
     and pattern_occurred
     and volume_is_high_in_the_last_bars

run_continues_trend_indication() =>
    index = 0
    [macdLine, signalLine, histogram] = ta.macd(close, 12, 26, 9)
    vol_avg = ta.sma(volume, 20)

    histogram_looks_good_3_pattern = histogram_looks_good(index, histogram, 3, vol_avg) and close[index] > open[index]
    histogram_looks_good_4_pattern = histogram_looks_good(index, histogram, 4, vol_avg) and close[index] > open[index]

    r_0_3_pattern = current_bar_is_strong_bar(index, 3)
    r_1_3_pattern = current_bar_is_strong_bar(index+1, 3)
    r_2_3_pattern = current_bar_is_strong_bar(index+2, 3)
    r_3_3_pattern = current_bar_is_strong_bar(index+3, 3)
    r_4_3_pattern = current_bar_is_strong_bar(index+4, 3)
    r_5_3_pattern = current_bar_is_strong_bar(index+5, 3)
    r_6_3_pattern = current_bar_is_strong_bar(index+6, 3)

    r_0_4_pattern = current_bar_is_strong_bar(index, 4)
    r_1_4_pattern = current_bar_is_strong_bar(index+1, 4)
    r_2_4_pattern = current_bar_is_strong_bar(index+2, 4)
    r_3_4_pattern = current_bar_is_strong_bar(index+3, 4)
    r_4_4_pattern = current_bar_is_strong_bar(index+4, 4)
    r_5_4_pattern = current_bar_is_strong_bar(index+5, 4)
    r_6_4_pattern = current_bar_is_strong_bar(index+6, 4)

    current_bar_is_strong_in_3_bars_pattern = false
    current_bar_is_strong_in_4_bars_pattern = false

    if histogram_looks_good_3_pattern and r_0_3_pattern
        current_bar_is_strong_in_3_bars_pattern := true
    else if histogram_looks_good_3_pattern and r_1_3_pattern
        current_bar_is_strong_in_3_bars_pattern := true
    else if histogram_looks_good_3_pattern and r_2_3_pattern
        current_bar_is_strong_in_3_bars_pattern := true
    else if histogram_looks_good_3_pattern and r_3_3_pattern
        current_bar_is_strong_in_3_bars_pattern := true
    else if histogram_looks_good_3_pattern and r_4_3_pattern
        current_bar_is_strong_in_3_bars_pattern := true
    else if histogram_looks_good_3_pattern and r_5_3_pattern
        current_bar_is_strong_in_3_bars_pattern := true
    else if histogram_looks_good_3_pattern and r_6_3_pattern
        current_bar_is_strong_in_3_bars_pattern := true

    if histogram_looks_good_4_pattern and r_0_4_pattern
        current_bar_is_strong_in_4_bars_pattern := true
    else if histogram_looks_good_4_pattern and r_1_4_pattern
        current_bar_is_strong_in_4_bars_pattern := true
    else if histogram_looks_good_4_pattern and r_2_4_pattern
        current_bar_is_strong_in_4_bars_pattern := true
    else if histogram_looks_good_4_pattern and r_3_4_pattern
        current_bar_is_strong_in_4_bars_pattern := true
    else if histogram_looks_good_4_pattern and r_4_4_pattern
        current_bar_is_strong_in_4_bars_pattern := true
    else if histogram_looks_good_4_pattern and r_5_4_pattern
        current_bar_is_strong_in_4_bars_pattern := true
    else if histogram_looks_good_4_pattern and r_6_4_pattern
        current_bar_is_strong_in_4_bars_pattern := true

    current_bar_is_strong = current_bar_is_strong_in_3_bars_pattern or current_bar_is_strong_in_4_bars_pattern

    // if (current_bar_is_strong_in_3_bars_pattern or current_bar_is_strong_in_4_bars_pattern) and hour >= 6 and hour < 15
    //     log.info("continues trend sign!")

    [current_bar_is_strong_in_3_bars_pattern, current_bar_is_strong_in_4_bars_pattern]

[current_bar_is_strong_in_3_bars_pattern, current_bar_is_strong_in_4_bars_pattern] = run_continues_trend_indication()

plotshape(hour >= 4 and hour < 15 ? current_bar_is_strong_in_3_bars_pattern : false, title="Continues trend indication 3 pattern", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = continues_trend_sign_3_pattern)
plotshape(hour >= 4 and hour < 15 ? current_bar_is_strong_in_4_bars_pattern : false, title="Continues trend indication 4 pattern", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = continues_trend_sign_4_pattern)



////           9 EMA Support Indication           ////
change_direction_up_indication_sign = "📈👆"

direction_has_changed_to_upward() =>
    index = 0
    ema_9 = ta.ema(close, 9)
    ema_20 = ta.ema(close, 20)
    vol_avg = ta.sma(volume, 20)
    vwap = ta.vwap(hlc3)

    current_bar_is_positive = close[index] > open[index] and low[index] > vwap[index] and volume[index] > 10000 and close[index] - open[index] > 0.1
    current_bar_touched_9_ema = low[index] <= ema_9[index] and close[index] > ema_9[index]
    current_bar_is_strong = (close[index] - open[index]) / (high[index] - close[index] + open[index] - low[index]) >= 0.6
    current_bar_changed_direction = high[index+1] < high[index]

    highest_high_index = 0
    highest_high_value = 0.0
    for i = index+10 to index+4
        if high[i] > highest_high_value and high[i] > high[i+1] and high[i] > high[i-1] and volume[i] >= vol_avg[i]
            highest_high_value := high[i]
            highest_high_index := i

    price_action_fixing_itself_towards_9_ema = true
    for i = highest_high_index-1 to index+1
        if i < 0 or i-1 < 0
            continue
        if i-1 != index and (high[i] < high[i-1] or low[i] < vwap[i] or low[i] < ema_20[i] or open[i] == close[i])
            price_action_fixing_itself_towards_9_ema := false
            break

    price_is_above_9_ema_until_now = true
    for i = highest_high_index-1 to index+1
        if i < 0
            continue
        if close[i] < ema_9[i] or open[i] < ema_9[i]
            price_is_above_9_ema_until_now := false
            break

    current_bar_close_is_lower_than_highest_high = close[index] < highest_high_value

    current_bar_looks_good = current_bar_is_positive and current_bar_touched_9_ema and current_bar_is_strong and current_bar_changed_direction and current_bar_close_is_lower_than_highest_high

    // if time == timestamp(relevant_timezone, year, 6, 26, 8, 16) and timeframe.period == "2"
    //     log.info("highest_high_index: {0}", highest_high_index)

    current_bar_looks_good and price_action_fixing_itself_towards_9_ema and price_is_above_9_ema_until_now

direction_has_changed_to_upward = direction_has_changed_to_upward()
if direction_has_changed_to_upward and hour >= 4 and hour < 15
    log.info("Direction has changed!")

plotshape(hour >= 4 and hour < 15 ? direction_has_changed_to_upward : false, title="Change Direction up", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = change_direction_up_indication_sign)

alertcondition(current_bar_is_strong_in_3_bars_pattern or current_bar_is_strong_in_4_bars_pattern or ema_support_indication or direction_has_changed_to_upward, title="Positive indication for long/short momentum", message="Positive indication for long/short momentum")
