// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © amiryaffe

//@version=6
indicator(title="Momentum Indicator for Day Trading", overlay = true)
import TradingView/ta/10

last_bars = 4
min_momentun_vol_avg = 5000
positive_sign = "✅"
positive_sign_without_ema = "📈"
negative_sign = "👮‍♂️"
buying_the_dip_sign = "📉🛒"


////           Negative indications           ////

current_bar_is_negative(index, close_src, open_src) =>
    close_src[index] < open_src[index]

current_bar_volume_is_high_than_usual(index, volume_src) =>
    vol_avg = ta.sma(volume_src[index], 20)
    volume_higher = volume_src[index] > vol_avg * 2

    volume_higher and volume_src[index] > volume_src[index+1]

current_bar_deletes_most_of_value_before(high_src, low_src, close_src, open_src, last_bars, index, volume_src) =>
    last_highest = 0.0
    for i = index to last_bars
        if high_src[index] > last_highest
            last_highest := high_src[index]

    last_lowest = last_highest
    for i = index to last_bars
        if low_src[index] <= last_lowest
            last_lowest := low_src[index]

    volume_higher = current_bar_volume_is_high_than_usual(index, volume_src)
    current_bar_is_negative = current_bar_is_negative(index, close_src, open_src)

    length = last_highest - last_lowest
    current_bar_length = high[index] - low[index]

    current_bar_length / length > 0.5 and current_bar_is_negative and volume_higher

current_bar_is_weak(index, close_src, open_src, volume_src) =>
    nine_ema = ta.ema(close_src, 9)
    volume_higher = current_bar_volume_is_high_than_usual(index, volume_src)
    current_bar_is_negative = current_bar_is_negative(index, close_src, open_src)
    (close_src[index] < nine_ema or open_src[index] < nine_ema) and current_bar_is_negative and volume_higher

current_bar_makes_new_low(index, volume_src, low_src, close_src, open_src) =>
    volume_higher = current_bar_volume_is_high_than_usual(index, volume_src)
    current_bar_is_negative = current_bar_is_negative(index, close_src, open_src)

    lowest_low = 100.0
    for i = index to 5
        if low_src[index+1] < lowest_low
            lowest_low := low_src[index+1]

    low_src[index] < lowest_low and current_bar_is_negative and volume_higher

current_bar_crosses_nine_ema(index, close_src, open_src) =>
    nine_ema = ta.ema(close_src, 9)
    twenty_ema = ta.ema(close_src, 20)

    vol_avg = ta.sma(volume, 20)
    volume_higher_than_avg = volume[index] > vol_avg

    open_src[index] > nine_ema and close_src[index] < nine_ema and volume_higher_than_avg

current_bar_dropped_its_majority_value(index) =>
    is_green_bar = close[index] > open[index]
    threshold = 0.2
    bar_is_weak = false

    if is_green_bar
        bar_is_weak := (close[index] - low[index]) / (high[index] - low[index]) < threshold
    else
        bar_is_weak := (open[index] - low[index]) / (high[index] - low[index]) < threshold

    bar_is_weak

run_negative_indicator(index) =>
    current_bar_is_weak = current_bar_is_weak(index, close[index], open[index], volume[index])
    current_bar_makes_new_low = current_bar_makes_new_low(index, low[index], volume[index], close[index], open[index])
    current_bar_deletes_most_of_value_before = current_bar_deletes_most_of_value_before(high[index], low[index], close[index], open[index], last_bars, index, volume[index])
    current_bar_crosses_nine_ema = current_bar_crosses_nine_ema(index, close[index], open[index])
    current_bar_dropped_its_majority_value = current_bar_dropped_its_majority_value(index)

    current_bar_is_weak
      or current_bar_makes_new_low
      or current_bar_deletes_most_of_value_before
      or current_bar_crosses_nine_ema
      or current_bar_dropped_its_majority_value

////           Positive indications           ////

current_bar_is_bullish(high_src, close_src, low_src, ema_9, ema_20, with_certainty) =>
    result = high_src - close_src < close_src - low_src
    if with_certainty
        result := result and low_src > ema_9 and low_src > ema_20
    else
        result := result and (low_src > ema_9 or low_src > ema_20)
    result

current_bar_volume_is_higher_than_last_ones(last_bars, close_src, open_src, volume_src, index) =>
    sum_of_buyers = 0.0
    sum_of_sellers = 0.0
    volume_is_higher_than_last_ones = true
    for i = 1 to last_bars
        if close_src[index + i] > open_src[index + i]
            sum_of_buyers += volume_src[index + i]
            continue
        else
            sum_of_sellers += volume_src[index + i]
            if volume_src[index + i] > volume_src
                volume_is_higher_than_last_ones := false

    volume_is_higher_than_last_ones or (sum_of_buyers > sum_of_sellers)

current_bar_is_above_vwap(vwap_src, close_src, high_src) =>
    close_src > vwap_src and high_src > vwap_src

current_ema_is_above_vwap(ema_9_src, vwap_src, open_src) =>
    rounded_vwap = (math.round(vwap_src * 100) / 100)
    rounded_9_ema = (math.round(ema_9_src * 100) / 100)
    rounded_open = (math.round(open_src * 100) / 100)

    rounded_9_ema >= rounded_vwap and rounded_open > rounded_vwap

last_bars_emas_higher(last_bars, ema_9_src, ema_20_src, vwap_src, index) =>
    last_bars_emas_higher = true
    for i = 0 to last_bars
        if not (math.max(ema_9_src[index + i], ema_20_src[index + i]) == ema_9_src[index + i])
            last_bars_emas_higher := false
            break

    last_bars_emas_higher

buyers_coming_in(last_bars, close_src, open_src, volume_src, index) =>
    vol_avg = ta.sma(volume_src[last_bars], 20)[index]
    sellers_are_still_in_the_game = false
    green_bars_volume = 0.0
    red_bars_volume = 0.0

    for i = 0 to last_bars
        bar_is_negative = close_src[index + i] < open_src[index + i]
        if bar_is_negative
            red_bars_volume += volume_src[i]
        else
            green_bars_volume += volume_src[i]
        if bar_is_negative and volume_src[i] > vol_avg
            sellers_are_still_in_the_game := true
            break

    negative_condition = sellers_are_still_in_the_game and (green_bars_volume / (green_bars_volume + red_bars_volume)) < 0.6

    not negative_condition

current_bar_has_new_high(high_src, index) =>
    highest_high = 0.0
    for i = 1 to 5
        if high_src[index+i] > highest_high
            highest_high := high_src[index+i]

    high_src > highest_high

inside_momentum(last_bars, close_src, open_src, volume_src, index, with_certainty) =>
    under_avg_vol_bars_counter = 0
    above_avg_vol_bars_counter = 0
    vol_avg = ta.sma(volume_src[last_bars], 20)[index]
    current_bar_volume_is_higher_than_last_ones = current_bar_volume_is_higher_than_last_ones(last_bars, close_src, open_src, volume_src, index)

    for i = 0 to last_bars
        if vol_avg[i] < min_momentun_vol_avg and with_certainty
            under_avg_vol_bars_counter += 1
        else if close_src < open_src
            under_avg_vol_bars_counter += 1
        else if current_bar_volume_is_higher_than_last_ones
            above_avg_vol_bars_counter += 1

    above_avg_vol_bars_counter > under_avg_vol_bars_counter and volume_src > vol_avg

current_bar_must_be_positive_and_volatile(last_bars, low_src, high_src, volume_src, close_src, open_src, index) =>
    current_bar_volume_is_higher_than_last_ones = current_bar_volume_is_higher_than_last_ones(last_bars, close_src, open_src, volume_src, index)
    rounded_low = math.round(low_src * 100) / 100
    rounded_high = math.round(high_src * 100) / 100
    vol_avg = ta.sma(volume_src, 20)[index]
    close_src > open_src and volume_src > vol_avg and current_bar_volume_is_higher_than_last_ones

current_bar_closes_where_buyers_still_in(close_src, low_src, high_src) =>
    close_src - low_src > high_src - close_src

current_bar_has_at_least_one_weak_bar_before(last_bars, close_src, open_src, high_src, low_src, index) =>
    has_weak_bar_before = false

    for i = 1 to last_bars
        if close_src[index+i] < open_src[index+i] or ((high_src[index+i] - close_src[index+i]) >= close_src[index+i] - low_src[index+i])
            has_weak_bar_before := true
            break
    has_weak_bar_before

current_bar_is_above_support_line(last_bars, low_src, index) =>
    current_bar_above_support_line = true
    for i = 1 to last_bars
        if low_src < low_src[index + i] - 2
            current_bar_above_support_line := false
            break
    current_bar_above_support_line

current_bar_close_to_nine_ema_by_avg(last_bars, close_src, low_src, high_src, ema_9, ema_20, index) =>
    current_bar_close_to_nine_ema_by_avg = false
    sum_ema_distances = 0.0

    for i = last_bars to 0
        sum_ema_distances += low_src[index+i] - ema_9[index+i]

    last_bars_ema_avg = sum_ema_distances / (last_bars+1)
    bar_size = high_src[index] - low_src[index]
    low_distance_from_ema = low_src[index] - ema_9[index]

    low_distance_from_ema_is_less_than_avg_distance = low_distance_from_ema <= last_bars_ema_avg
    avg_distance_divided_by_low_distance_from_ema_is_less_than_pointfive = last_bars_ema_avg / low_distance_from_ema <= 0.5

    ((low_distance_from_ema_is_less_than_avg_distance or avg_distance_divided_by_low_distance_from_ema_is_less_than_pointfive) and low_distance_from_ema / bar_size <= 0.5) or
      (low_src[index] > ema_20[index] and low_src[index] < ema_9[index])

current_bar_bigger_than_last_red_candle_body(last_bars, close_src, open_src, index) =>
    current_bar_bigger = true
    for i = 1 to last_bars
        if close_src[index + i] > open_src[index + i]
            continue
        else if open_src[index + i] - close_src[index + i] > close_src - open_src
            current_bar_bigger := false
            break

    current_bar_bigger

current_bar_macd_is_positive(close_src, index) =>
    macd_is_positive = false

    [macdLine, signalLine, histogram] = ta.macd(close_src, 12, 26, 9)
    macd_current_is_positive = macdLine[index] > 0 and macdLine[index] > signalLine[index] and histogram[index] > 0.005

    macd_crossed_recently = false

    macd_crossed_last_bars = 10
    for i = 1 to macd_crossed_last_bars
        bar_before_is_weak_but_above_zero_line = histogram[index+i] < histogram[index] and macdLine[index+i] >= 0
        macd_crossed_recently := macdLine[index] > 0 and histogram[index] > histogram[index+i] and bar_before_is_weak_but_above_zero_line
        if macd_crossed_recently
            break

    highest_macdLine_before = 0.0
    highest_macdLine_index = 0
    bars_back = 20

    for i = bars_back to 1
        if macdLine[index+i] > macdLine[index+i+1] and macdLine[index+i] > macdLine[index+i-1] and signalLine[index+i+1] > 0 and signalLine[index+i-1] > 0 and histogram[index+i] > 0
            if highest_macdLine_before < macdLine[index+i]
                highest_macdLine_before := macdLine[index+i]
                highest_macdLine_index := index+i

    if highest_macdLine_index != 0
        // histogram check
        highest_histogram = 0.0
        for i = 1 to 15
            if histogram[index+i] > highest_histogram
                highest_histogram := histogram[index+i]

        // log.info("highest_histogram: {0}. c_h: {1}. r: {2}", highest_histogram, histogram[index], histogram[index]/highest_histogram)
        if histogram[index]/highest_histogram >= 0.6 and histogram[index] >= histogram[index+1] * 1.2
            highest_histogram_index = 0
            start_histogram_index = 0
            end_histogram_index = 0
            var float start_momentum_histogram = na
            var float end_momentum_histogram = na
            for i = bars_back to 1
                if histogram[index+i] < 0
                    continue
                if histogram[index+i] > 0 and histogram[index+i+1] < 0
                    start_momentum_histogram := histogram[index+i]
                    start_histogram_index := index+i
                if histogram[index+i] == highest_histogram
                    highest_histogram_index := index+i
                if histogram[index+i] < histogram[index+i+1] and histogram[index+i] < histogram[index+i - 1] and start_histogram_index > index+i
                    end_histogram_index := index+i
                    end_momentum_histogram := histogram[index+i]

            most_process_already_finished = false
            if end_histogram_index < start_histogram_index
                most_process_already_finished := math.abs(highest_histogram_index - start_histogram_index) * 1.5 < math.abs(end_histogram_index - highest_histogram_index)

            // log.info("highest_histogram_index: {0}. highest_histogram: {1}. start_histogram_index: {2}. end_histogram_index: {3}", highest_histogram_index, highest_histogram, start_histogram_index, end_histogram_index)
            lowest_macdLine = highest_macdLine_before
            for i = index to highest_macdLine_index
                if macdLine[index+i] < lowest_macdLine
                    lowest_macdLine := macdLine[index+i]

            // log.info("h: {0}. h_i: {1}. l: {2}, p: {3}", highest_macdLine_before,highest_macdLine_index, lowest_macdLine, lowest_macdLine/highest_macdLine_before)
            macd_fixed_less_than_50_percent = lowest_macdLine/highest_macdLine_before >= 0.4 and lowest_macdLine/highest_macdLine_before < 0.999 and not (highest_macdLine_before * 4 < macdLine[index])
            // log.info("macd_current_is_positive: {0}. macd_crossed_recently: {1}. macd_current_is_positive: {2}. macd_fixed_less_than_50_percent: {3}", macd_current_is_positive, macd_crossed_recently, macd_current_is_positive, macd_fixed_less_than_50_percent)
            macd_is_positive := macd_current_is_positive and macd_crossed_recently and macd_current_is_positive and macd_fixed_less_than_50_percent and not most_process_already_finished

        macd_is_positive

current_macd_has_new_high_and_came_as_change_point(close_src, index) =>
    [macdLine, signalLine, histogram] = ta.macd(close_src, 12, 26, 9)
    previous_bars_has_change_in_momentum = false

    highest_histogram = 0.0
    for i = 1 to 8
        if histogram[index+i] > highest_histogram
            highest_histogram := histogram[index+i]

    for i = 1 to 3
        if histogram[index+i] < 0
            continue

        current_histogram_is_high = true
        for j = 1 to 3
            current_histogram_is_high := histogram[index] > histogram[index+j] and histogram[index+j] > 0
            if not current_histogram_is_high
                break
        if not current_histogram_is_high
            false

        last_histogram_is_between_two_highs = histogram[index+i] < histogram[index+i+1] and histogram[index+i] < histogram[index+i-1] and histogram[index+i] > 0 and histogram[index+i] > 0 and histogram[index+i+1] < histogram[index]
        all_are_in_the_same_session = dayofmonth[index] == dayofmonth[index+i] and dayofmonth[index+i] == dayofmonth[index+i+1] and dayofmonth[index+i+1] == dayofmonth[index+i-1]
        macd_is_positive = macdLine[index+i] > 0
        histogram_is_positive = histogram[index+i] > 0
        current_macd_is_bigger = macdLine[index] > macdLine[index+i]
        current_histogram_is_bigger = histogram[index] > histogram[index+i] and highest_histogram < histogram[index]
        if last_histogram_is_between_two_highs and macd_is_positive and histogram_is_positive and current_macd_is_bigger and current_histogram_is_bigger and all_are_in_the_same_session and current_histogram_is_high
            previous_bars_has_change_in_momentum := true
            break

    previous_bars_has_change_in_momentum

current_bar_touching_9_ema(low_src, ema_9, index) =>
    low_src[index] <= ema_9[index] or (math.abs(low_src[index] - ema_9[index]) <= 0.10)

current_bar_is_at_the_beginning_of_the_day(index) =>
    // checks if it still in the beginning and also if it right before market opening
    still_in_the_beginning = false
    current_timeframe = str.tonumber(timeframe.period)
    bars_back = 15
    if current_timeframe == 2
        bars_back := 10
    if current_timeframe > 2
        bars_back := 5
    for i = bars_back to 1
        if (time[i-1] - time[i])/1000/60/current_timeframe > current_timeframe * 10
            //log.info("minutes_between_bars: {0}", (time[i] - time[i-1])/1000/60)
            still_in_the_beginning := true
            break
        if hour[index+i] == 9 and minute[index+i] >= 30 and minute[index+i] < 50
            still_in_the_beginning := true
            break

    still_in_the_beginning

current_bar_gets_50_percent_above_9_ema(close_src, low_src, ema_9) =>
    close_src - ema_9 > ema_9 - low_src

last_bars_volume_is_higher(index, last_bars, volume_src) =>
    vol_avg = ta.sma(volume_src, 20)

    last_highest_vol_avg = 0.0
    volumer_is_getting_higher = true
    for i = last_bars to 0
        if vol_avg[index+i] < last_highest_vol_avg and last_highest_vol_avg != 0.0
            volumer_is_getting_higher := false
            break
        last_highest_vol_avg := vol_avg[index+i]

    volumer_is_getting_higher := last_highest_vol_avg > 0.0

    current_bar_volume_is_much_bigger_than_previous_bar = false
    if volume_src[index+1] / volume_src[index] < 0.8
        current_bar_volume_is_much_bigger_than_previous_bar := true

    current_vol_avg_is_biggest_by_multiply_from_lowest = false
    highest_vol_avg = 0.0
    // instead of ta.highest function which does not work properly always
    for i = 0 to last_bars
        if vol_avg[index+i] > highest_vol_avg
            highest_vol_avg := vol_avg[index+i]

    // instead of ta.lowest function which does not work properly always
    lowest_vol_avg = highest_vol_avg
    for i = 0 to last_bars
        if vol_avg[index+i] < lowest_vol_avg
            lowest_vol_avg := vol_avg[index+i]

    if highest_vol_avg / lowest_vol_avg >= 1.3 or lowest_vol_avg / highest_vol_avg <= 0.5
        current_vol_avg_is_biggest_by_multiply_from_lowest := true

    //log.info("volumer_is_getting_higher: {0}. current_vol_avg_is_biggest_by_multiply_from_lowest: {1}. current_bar_volume_is_much_bigger_than_previous_bar: {2}. h/l: {3}. h: {4}. low: {5}", volumer_is_getting_higher,current_vol_avg_is_biggest_by_multiply_from_lowest,current_bar_volume_is_much_bigger_than_previous_bar, highest_vol_avg / lowest_vol_avg, highest_vol_avg, lowest_vol_avg)

    volumer_is_getting_higher and current_vol_avg_is_biggest_by_multiply_from_lowest and current_bar_volume_is_much_bigger_than_previous_bar

current_bar_volume_is_higher_for_fast_change(index, volume_src, high_src, low_src) =>
    minimum_volume_per_bar = 5000
    volume_src[index] >= minimum_volume_per_bar and high_src[index] - low_src[index] >= 0.1

no_bearish_bar_detected_in_the_last_bars(last_bars) =>
    at_least_one_bar_is_weak = false
    for i = 1 to last_bars
        at_least_one_bar_is_weak := run_negative_indicator(i)
        if at_least_one_bar_is_weak
            break

    not at_least_one_bar_is_weak

last_biggest_volume_bar_was_green(volume_src, close_src, open_src, high_src, low_src, last_bars, with_certainty) =>
    start_index = 0
    if with_certainty
        start_index := 1

    highest_bar_volume = 0.0
    for i = start_index to last_bars
        if volume_src[i] > highest_bar_volume
            highest_bar_volume := volume_src[i]

    highest_volume_bar_is_green = false

    for i = start_index to last_bars
        if volume_src[i] == highest_bar_volume and close_src[i] > open_src[i] and ((high_src[i] - close_src[i]) / (high_src[i] - low_src[i]) < 0.6)
            highest_volume_bar_is_green := true
            break

    highest_volume_bar_is_green

current_bar_close_to_9_ema_on_other_timeframes_as_well(index, ema_9, low_src, close_src, vwap_src) =>
    ema_9_at_2_minute_timeframe = request.security(syminfo.tickerid, "2", ema_9, lookahead=barmerge.lookahead_on)
    vwap_at_2_minute_timeframe = request.security(syminfo.tickerid, "2", vwap_src, lookahead=barmerge.lookahead_on)

    low_2_min = request.security(syminfo.tickerid, "2", low_src, lookahead=barmerge.lookahead_on)

    not_far_from_9_ema_on_bigger_timeframes = true
    close_distance = 0.20

    m_2_distance = math.abs(low_2_min - ema_9_at_2_minute_timeframe)
    m_1_distance = math.abs(low_src[index] - ema_9[index])
    m_2_vwap_distance = math.abs(low_2_min - vwap_at_2_minute_timeframe)
    two_minute_chart_is_close_to_9_ema = m_2_distance <= close_distance or m_1_distance <= close_distance
    two_minute_chart_is_close_to_vwap = m_2_vwap_distance <= close_distance

    if timeframe.period == "1"
        not_far_from_9_ema_on_bigger_timeframes := two_minute_chart_is_close_to_9_ema or two_minute_chart_is_close_to_vwap

    not_far_from_9_ema_on_bigger_timeframes

///////// buying the dip indicators /////////
last_bars_crossed_9_ema_but_didnt_closed_under_it(index, close_src, low_src, high_src, last_bars, ema_9, ema_20) =>
    some_last_bars_closed_under_9_ema = false

    for i = 1 to last_bars
        closed_under_9_ema = close_src[index+i] < ema_9[index+i]
        closed_under_20_ema = close_src[index+i] < ema_20[index+i]
        if closed_under_9_ema and closed_under_20_ema
            some_last_bars_closed_under_9_ema := true
            break

    rounded_9_ema = (math.round(ema_9 * 100) / 100)
    rounded_low = (math.round(low_src * 100) / 100)
    rounded_close = (math.round(close_src * 100) / 100)

    low_is_stronger_than_9_ema_but_close = rounded_low[index] <= rounded_9_ema[index]
    low_is_stronger_than_9_ema_but_close and rounded_close[index] > rounded_9_ema[index] and not some_last_bars_closed_under_9_ema

current_bar_close_is_not_highest(index, high_src, close_src) =>
    last_highest_high = 0.0
    for i = index to 10
        if high_src[index+1] > last_highest_high
            last_highest_high := high_src[index+1]

    close_src[index] <= last_highest_high

///////// run indicators /////////

run_positive_indicator(i, with_certainty) =>
    vwap_index = ta.vwap(hlc3)[i]
    ema_9_index = ta.ema(close, 9)[i]
    ema_20_index = ta.ema(close, 20)[i]

    open_index = open[i]
    close_index = close[i]
    high_index = high[i]
    low_index = low[i]
    volume_index = volume[i]

    current_bar_is_above_vwap = current_bar_is_above_vwap(vwap_index, close_index, high_index)
    last_bars_emas_higher = last_bars_emas_higher(last_bars, ema_9_index, ema_20_index, vwap_index, i)
    current_ema_is_above_vwap = current_ema_is_above_vwap(ema_9_index, vwap_index, open_index)
    current_bar_has_new_high = current_bar_has_new_high(high_index, i)
    buyers_coming_in = buyers_coming_in(last_bars, close_index, open_index, volume_index, i)
    inside_momentum = inside_momentum(last_bars, close_index, open_index, volume_index, i, true)
    current_bar_has_at_least_one_weak_bar_before = current_bar_has_at_least_one_weak_bar_before(last_bars, close_index, open_index, high_index, low_index, i)
    current_bar_must_be_positive_and_volatile = current_bar_must_be_positive_and_volatile(last_bars, low_index, high_index, volume_index, close_index, open_index, i)
    current_bar_is_above_support_line = current_bar_is_above_support_line(3, low_index, i)
    current_bar_close_to_nine_ema_by_avg = current_bar_close_to_nine_ema_by_avg(last_bars, close_index, low_index, high_index, ema_9_index, ema_20_index, i)
    current_bar_macd_is_positive = current_bar_macd_is_positive(close_index, i)
    current_bar_gets_50_percent_above_9_ema = current_bar_gets_50_percent_above_9_ema(close_index, low_index, ema_9_index)
    current_bar_closes_where_buyers_still_in = current_bar_closes_where_buyers_still_in(close_index, low_index, high_index)
    current_bar_is_bullish = current_bar_is_bullish(high_index, close_index, low_index, ema_9_index, ema_20_index, true)
    last_bars_volume_is_higher = last_bars_volume_is_higher(i, 10, volume_index)
    last_biggest_volume_bar_was_green = last_biggest_volume_bar_was_green(volume_index, close_index, open_index, high_index, low_index, 5, true)
    current_bar_close_to_9_ema_on_other_timeframes_as_well = current_bar_close_to_9_ema_on_other_timeframes_as_well(i, ema_9_index, low_index, close_index, vwap_index)

    if with_certainty
        current_bar_is_above_vwap
          and current_ema_is_above_vwap
          and last_bars_emas_higher
          and current_bar_has_new_high
          and buyers_coming_in
          and inside_momentum
          and current_bar_has_at_least_one_weak_bar_before
          and current_bar_must_be_positive_and_volatile
          and current_bar_is_above_support_line
          and current_bar_close_to_nine_ema_by_avg
          and current_bar_macd_is_positive
          and current_bar_gets_50_percent_above_9_ema
          and current_bar_closes_where_buyers_still_in
          and current_bar_is_bullish
          and last_bars_volume_is_higher
          and last_biggest_volume_bar_was_green
          and current_bar_close_to_9_ema_on_other_timeframes_as_well
    else
        current_bar_touching_9_ema = current_bar_touching_9_ema(low_index, ema_9_index, i)
        current_macd_has_new_high_and_came_as_change_point = current_macd_has_new_high_and_came_as_change_point(close_index, i)
        current_bar_is_bullish_without_ema_certainty = current_bar_is_bullish(high_index, close_index, low_index, ema_9_index, ema_20_index, false)
        last_biggest_volume_bar_was_green_without_certainty = last_biggest_volume_bar_was_green(volume_index, close_index, open_index, high_index, low_index, 5, false)
        inside_momentum_without_certainty = inside_momentum(last_bars, close_index, open_index, volume_index, i, false)
        current_bar_is_at_the_beginning_of_the_day = current_bar_is_at_the_beginning_of_the_day(i)
        current_bar_volume_is_higher_for_fast_change = current_bar_volume_is_higher_for_fast_change(i, volume_index, high_index, low_index)

        current_bar_is_above_vwap
          and current_bar_touching_9_ema
          and last_bars_emas_higher
          and current_bar_has_new_high
          and buyers_coming_in
          and inside_momentum_without_certainty
          and current_bar_has_at_least_one_weak_bar_before
          and current_bar_must_be_positive_and_volatile
          and current_bar_is_above_support_line
          and current_bar_close_to_nine_ema_by_avg
          and current_macd_has_new_high_and_came_as_change_point
          and current_bar_gets_50_percent_above_9_ema
          and current_bar_closes_where_buyers_still_in
          and current_bar_is_bullish_without_ema_certainty
          and last_bars_volume_is_higher
          and last_biggest_volume_bar_was_green_without_certainty
          and current_bar_is_at_the_beginning_of_the_day
          and current_bar_volume_is_higher_for_fast_change

run_buying_the_dip_indication(i) =>
    vwap_index = ta.vwap(hlc3)[i]
    ema_9_index = ta.ema(close, 9)[i]
    ema_20_index = ta.ema(close, 20)[i]

    open_index = open[i]
    close_index = close[i]
    high_index = high[i]
    low_index = low[i]
    volume_index = volume[i]

    last_bars_crossed_9_ema_but_didnt_closed_under_it = last_bars_crossed_9_ema_but_didnt_closed_under_it(i, close_index, low_index, high_index, 2, ema_9_index, ema_20_index)
    current_bar_close_is_not_highest = current_bar_close_is_not_highest(i, high_index, close_index)
    current_bar_is_above_vwap = current_bar_is_above_vwap(vwap_index, close_index, high_index)
    last_bars_emas_higher = last_bars_emas_higher(last_bars, ema_9_index, ema_20_index, vwap_index, i)
    current_bar_has_new_high = current_bar_has_new_high(high_index, i)
    current_bar_has_at_least_one_weak_bar_before = current_bar_has_at_least_one_weak_bar_before(last_bars, close_index, open_index, high_index, low_index, i)
    current_bar_must_be_positive_and_volatile = current_bar_must_be_positive_and_volatile(last_bars, low_index, high_index, volume_index, close_index, open_index, i)
    current_bar_volume_is_high_than_usual = current_bar_volume_is_high_than_usual(i, volume_index)
    last_bars_volume_is_higher = last_bars_volume_is_higher(i, 10, volume_index)

    last_bars_crossed_9_ema_but_didnt_closed_under_it
      and current_bar_close_is_not_highest
      and current_bar_is_above_vwap
      and last_bars_emas_higher
      and current_bar_has_new_high
      and current_bar_has_at_least_one_weak_bar_before
      and current_bar_must_be_positive_and_volatile
      and current_bar_volume_is_high_than_usual
      and last_bars_volume_is_higher

positive_indication = run_positive_indicator(0, true)
positive_indication_without_certainty = run_positive_indicator(0, false)

plotshape(positive_indication, title="Positive indication with certainty", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = positive_sign)
plotshape(positive_indication_without_certainty, title="Positive indication without certainty", color=color.blue, display = display.pane, style = shape.arrowup, size = size.small, location = location.belowbar, text = positive_sign_without_ema)
plotshape(run_negative_indicator(0), title="Negative indication", color=color.red, display = display.pane, style = shape.arrowdown, size = size.small, location = location.abovebar, text = negative_sign)

alertcondition(positive_indication or positive_indication_without_certainty, title="Positive indication with or without certainty", message="Positive indication with or without certainty")
