// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © amiryaffe

//@version=6
indicator(title="Momentum Indicator for Day Trading", overlay = true)
import TradingView/ta/10


relevant_timezone = "America/New_York"


////           Breaks Last High Indication           ////
breaks_last_high_sign_to_show = "✅"
breaks_last_high_sign_to_show_number_1 = "✅ AND highest far from start"
breaks_last_high_sign_to_show_number_2 = "✅ AND start is far from current bar"
breaks_last_high_sign_to_show_number_3 = "✅ AND too high from highest bar"
breaks_last_high_sign_to_show_number_4 = "✅ AND highest bar is weak"

breaks_last_high_indication(index) =>
    ema_9 = ta.ema(close, 9)
    vwap = ta.vwap(hlc3)
    vol_avg = ta.sma(volume, 20)

    bars_back = 30
    if str.tonumber(timeframe.period) >= 5
        bars_back := 15

    highest_high_value = 0.0
    highest_high_index = 0
    biggest_bar_value = 0.0
    biggest_bar_index = 0

    current_timeframe = str.tonumber(timeframe.period)
    market_start_time = timestamp(relevant_timezone, year, month, dayofmonth, 9, 30)

    last_bars_has_time_gaps = false
    start_of_trend_bar_index = 0
    for i = index+bars_back to index
        if i-1 < 0 or i-2 < 0
            continue

        last_bar_has_time_gap = (time[i-1] - time[i])/1000/60 > current_timeframe
        current_bar_start_the_trend = (time[i-2] - time[i-1])/1000/60 == current_timeframe
        if last_bar_has_time_gap and current_bar_start_the_trend and time < market_start_time
            last_bars_has_time_gaps := true
            start_of_trend_bar_index := i-1

    for i = index+bars_back to index
        if i-1 < 0
            continue
        bar_is_volatile = volume[i-1] > volume[i] * 50 and volume[i-1] > vol_avg[i-1]
        if bar_is_volatile
            last_bars_has_time_gaps := true
            start_of_trend_bar_index := i-1

    for i = start_of_trend_bar_index to index+1
        if i-1 < 0
            continue
        if high[i] > highest_high_value+0.01 and high[i] > high[i+1] and high[i] > high[i-1] and ((high[i]-low[i])/biggest_bar_value >= 0.8 or start_of_trend_bar_index - i <= 3)
            highest_high_value := high[i]
            highest_high_index := i
        if high[i] - low[i] > biggest_bar_value and (high[i+1] - low[i+1])/(high[i] - low[i]) <= 0.7
            biggest_bar_value := high[i] - low[i]
            biggest_bar_index := i

    min_distance_from_big_bar = 4
    if str.tonumber(timeframe.period) > 2
        min_distance_from_big_bar := 2

    fixed_more_than_enough = true
    trend_started_way_too_strong = false
    if start_of_trend_bar_index != 0 and (current_timeframe == 1 or current_timeframe == 2)
        total_up_trend = high[highest_high_index] - low[start_of_trend_bar_index]

        lowest_from_highest_value = highest_high_value
        lowest_from_highest_index = 0

        for i = highest_high_index-1 to index+1
            if i < 0
                continue
            if low[i] < lowest_from_highest_value
                lowest_from_highest_value := low[i]
                lowest_from_highest_index := i

        fixed_more_than_enough := (close[highest_high_index]-lowest_from_highest_value)/total_up_trend <= 0.7
        if not fixed_more_than_enough and close[highest_high_index] < open[highest_high_index]
            fixed_more_than_enough := true

        trend_started_way_too_strong := true
        for i = start_of_trend_bar_index to highest_high_index
            start_to_high_is_short = start_of_trend_bar_index - highest_high_index <= 2
            current_bar_is_stronger_than_highest_bar = open[index] > close[highest_high_index]
            if current_bar_is_stronger_than_highest_bar and (close[i] < open[i] or (close[i] - open[i])/(high[i] - low[i]) <= 0.4 or start_to_high_is_short)
                trend_started_way_too_strong := false
                break

    biggest_bar_is_strong = math.abs(close[biggest_bar_index] - open[biggest_bar_index])/math.abs(high[biggest_bar_index] - close[biggest_bar_index] + open[biggest_bar_index] - low[biggest_bar_index]) >= 0.5
    highest_bar_is_strong = math.abs(close[highest_high_index] - open[highest_high_index])/math.abs(high[highest_high_index] - close[highest_high_index] + open[highest_high_index] - low[highest_high_index]) >= 0.5

    biggest_bar_is_the_first_bar_in_the_session = (dayofmonth[biggest_bar_index] != dayofmonth[biggest_bar_index+1] or volume[biggest_bar_index] > volume[biggest_bar_index+1] * 50 or last_bars_has_time_gaps) and biggest_bar_index - highest_high_index < 5 and biggest_bar_index - index >= min_distance_from_big_bar

    low_is_still_high = true
    no_bar_crossed_yet_highest_bar = true
    didnt_crossed_down_9_ema = true
    didnt_crossed_down_vwap = true
    at_least_one_red_bar = (close[highest_high_index] <= open[highest_high_index] and high[highest_high_index] != low[highest_high_index]) or (math.abs(close[highest_high_index]-open[highest_high_index])/(high[highest_high_index]-low[highest_high_index])) <= 0.05

    for i = highest_high_index-1 to index
        if i < 0
            continue
        if low[i]/highest_high_value <= 0.4
            low_is_still_high := false
        if ((i > index and current_timeframe > 1) or (i > index+1 and current_timeframe == 1)) and high[i] > highest_high_value+0.01 and volume[index] < volume[i]
            no_bar_crossed_yet_highest_bar := false
        if close[i] < ema_9[i]
            didnt_crossed_down_9_ema := false
        if close[i] < vwap[i] and close[i] < ema_9[i]
            didnt_crossed_down_vwap := false
        if close[i] < open[i] or (math.abs(close[i]-open[i])/(high[i]-low[i])) <= 0.05
            at_least_one_red_bar := true

    at_least_one_bar_is_red = false
    for i = highest_high_index to index
        if (close[i] < open[i] or (close[i] - open[i])/(high[i] - low[i]) <= 0.2) or str.tonumber(timeframe.period) == 15
            at_least_one_bar_is_red := true

    lowest_price_in_last_bars = ta.lowest(low, 20)
    highest_price_in_last_bars = ta.highest(close, 20)
    current_bar_continues_up_trend = (highest_price_in_last_bars-lowest_price_in_last_bars) / close[index] >= 0.15

    current_bar_is_positive = close[index] > open[index] and open[index] > ema_9[index] and volume[index] >= vol_avg[index] and vol_avg[index] > 10000
    current_bar_crossed_last_high = (low[index] < highest_high_value) or (low[index+1] < highest_high_value)
    curret_bar_is_strong = (close[index] - open[index])/(high[index] - close[index] + open[index] - low[index]) > 0.33 and volume[index] >= 50000

    biggest_and_highest_are_the_same_but_strong = biggest_bar_index == highest_high_index and math.abs(close[highest_high_index]-open[highest_high_index])/math.abs(high[highest_high_index]-close[highest_high_index]) >= 0.4

    current_bar_is_similar_in_size_for_highest_one = ((close[index]-open[index])/(close[highest_high_index]-open[highest_high_index]) >= 0.5) or volume[index] > volume[highest_high_index] * 1.2

    current_bar_is_stronger_than_highest_bar = true
    if close[highest_high_index] > open[index]
        current_bar_is_stronger_than_highest_bar := (high[highest_high_index] - open[index])/(high[index]-low[index]) <= 0.3

    bar_before_does_not_decide_yet = (close[index+1] - open[index+1])/(high[index+1] - low[index+1]) < 0.6 and (current_timeframe == 1 or current_timeframe == 2) and volume[index] < volume[index+1] * 3

    breaks_last_high_indication = close[index] > highest_high_value
     and low_is_still_high
     and current_bar_is_positive
     and current_bar_crossed_last_high
     and biggest_bar_is_the_first_bar_in_the_session
     and no_bar_crossed_yet_highest_bar
     and didnt_crossed_down_9_ema
     and at_least_one_red_bar
     and didnt_crossed_down_vwap
     and (biggest_bar_is_strong or highest_bar_is_strong or biggest_and_highest_are_the_same_but_strong or volume[index] > volume[index+1] * 7)
     and curret_bar_is_strong
     and current_bar_continues_up_trend
     and at_least_one_bar_is_red
     and current_bar_is_similar_in_size_for_highest_one
     and fixed_more_than_enough
     and not trend_started_way_too_strong
     and current_bar_is_stronger_than_highest_bar
     and not bar_before_does_not_decide_yet

    // if breaks_last_high_indication
    //     log.info("start_of_trend_bar_index: {0}. highest_high_index: {1}. ", start_of_trend_bar_index, highest_high_index)

    highest_bar_is_weak = (high[highest_high_index] - low[highest_high_index])/(high[highest_high_index+1] - low[highest_high_index+1]) < 0.6

    number_to_show = 0
    if not (low[index] < high[highest_high_index] or low[index+1] < high[highest_high_index])
        number_to_show := 3
    if highest_bar_is_weak
        number_to_show := 4

    if current_timeframe == 5
        highest_bar_is_close_to_trend_start_bar = start_of_trend_bar_index - highest_high_index < 4
        if not highest_bar_is_close_to_trend_start_bar
            number_to_show := 1
        if not (start_of_trend_bar_index - index <= 10)
            number_to_show := 2

    if current_timeframe == 15
        highest_bar_is_close_to_trend_start_bar = start_of_trend_bar_index - highest_high_index < 3
        if not highest_bar_is_close_to_trend_start_bar
            number_to_show := 1
        if not (start_of_trend_bar_index - index <= 6)
            number_to_show := 2

    [breaks_last_high_indication, number_to_show]

[breaks_last_high_indication, sign_to_show_number] = breaks_last_high_indication(0)

plotshape(hour >= 4 and hour < 15 and sign_to_show_number == 0 ? breaks_last_high_indication : false, title="Breaks New High Indication", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = breaks_last_high_sign_to_show)
plotshape(hour >= 4 and hour < 15 and sign_to_show_number == 1 ? breaks_last_high_indication : false, title="Breaks New High Indication", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = breaks_last_high_sign_to_show_number_1)
plotshape(hour >= 4 and hour < 15 and sign_to_show_number == 2 ? breaks_last_high_indication : false, title="Breaks New High Indication", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = breaks_last_high_sign_to_show_number_2)
plotshape(hour >= 4 and hour < 15 and sign_to_show_number == 3 ? breaks_last_high_indication : false, title="Breaks New High Indication", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = breaks_last_high_sign_to_show_number_3)
plotshape(hour >= 4 and hour < 15 and sign_to_show_number == 4 ? breaks_last_high_indication : false, title="Breaks New High Indication", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = breaks_last_high_sign_to_show_number_4)

////           9 EMA Support Indication           ////

ema_support_indication_sign = "🛫👆"

ema_support_indication(index) =>
    [macdLine, signalLine, histogram] = ta.macd(close, 12, 26, 9)
    vol_avg = ta.sma(volume, 20)
    ema_9 = ta.ema(close, 9)
    vwap = ta.vwap(hlc3)

    current_bar_is_highest = true
    ema_was_crossed_down = false
    for i = index+6 to index+1
        if high[i] > close[index]
            current_bar_is_highest := false
        if close[i] < ema_9[i]
            ema_was_crossed_down := true

    bars_prices_are_similar_counter = 0
    for i = index+6 to index+1
        current_close_inside_previus_range = close[i] <= high[i+1] and close[i] >= low[i+1]
        if current_close_inside_previus_range
            bars_prices_are_similar_counter += 1

    bars_price_range_is_different = bars_prices_are_similar_counter <= 4

    last_highest_value = 0.0
    last_highest_index = 0
    for i = index+10 to index+2
        is_between_two_lows = high[i] > high[i+1] and high[i] > high[i-1]
        red_bar_right_after = close[i-1] < open[i-1] and volume[i]/volume[i-1] <= 0.6
        if high[i] > last_highest_value and is_between_two_lows and not (red_bar_right_after and volume[i] < volume[i-1])
            last_highest_value := high[i]
            last_highest_index := i

    highest_is_on_weak_bar = false
    if last_highest_index != 0 and close[last_highest_index] < open[last_highest_index]
        highest_is_on_weak_bar := true

    at_least_one_bar_is_red = false
    no_weak_bar_between = true
    for i = last_highest_index to index
        if (close[i] < open[i] or (close[i] - open[i])/(high[i] - low[i]) <= 0.2) or str.tonumber(timeframe.period) == 15
            at_least_one_bar_is_red := true
        if close[i] > open[i] and volume[i] < 10000
            no_weak_bar_between := false

    lowest_price_in_last_bars = ta.lowest(low, 20)
    highest_price_in_last_bars = ta.highest(close, 20)
    current_bar_continues_up_trend = (highest_price_in_last_bars-lowest_price_in_last_bars) / close[index] >= 0.15
    // if time == timestamp(relevant_timezone, year, 6, 25, 9, 49) and timeframe.period == "1"
    //     log.info("l: {0}. h: {1}. r: {2}. p: {3}", lowest_price_in_last_bars, highest_price_in_last_bars, highest_price_in_last_bars-lowest_price_in_last_bars, (highest_price_in_last_bars-lowest_price_in_last_bars) / close[index])

    above_vwap = close[index] > vwap[index] and close[index+1] > vwap[index+1]
    macd_is_positive = macdLine[index] > 0 and histogram[index] > 0 and histogram[index] > histogram[index+1]
    previous_bar_is_strong = close[index+1] > close[index+2] and close[index+1] > open[index+2] and close[index+1] > open[index+1]
    buyers_coming_in = previous_bar_is_strong and volume[index] > (volume[index+1] * 2) and volume[index] > vol_avg[index] and vol_avg[index] > 100000 and vol_avg[index+1] >= 50000 and (close[index] - open[index]) > (high[index] - close[index]) and (high[index] - low[index])/(close[index+1] - open[index+1]) >= 0.9
    bar_full_body_is_strong_than_candles = (open[index]-low[index])/(close[index]-open[index]) <= 0.33
    bar_is_positive = bar_full_body_is_strong_than_candles and close[index] > open[index] and high[index] > high[index+1] and open[index] > open[index+1]
    ema_is_supporting = math.abs(ema_9[index+1] - low[index+1])/(close[index]-low[index]) <= 0.2 and not ema_was_crossed_down

    ema_support_indication = macd_is_positive
     and above_vwap
     and buyers_coming_in
     and bar_is_positive
     and ema_is_supporting
     and current_bar_is_highest
     and current_bar_continues_up_trend
     and bars_price_range_is_different
     and at_least_one_bar_is_red
     and not highest_is_on_weak_bar
     and no_weak_bar_between

    ema_support_indication

ema_support_indication = ema_support_indication(0)

plotshape(hour >= 4 and hour < 15 ? ema_support_indication : false, title="EMA Support Indication", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.belowbar, text = ema_support_indication_sign)


////           9 EMA Support Indication           ////
change_direction_up_indication_sign = "📈👆"

direction_has_changed_to_upward() =>
    index = 0
    ema_9 = ta.ema(close, 9)
    ema_20 = ta.ema(close, 20)
    vol_avg = ta.sma(volume, 20)
    vwap = ta.vwap(hlc3)

    current_timeframe = str.tonumber(timeframe.period)

    last_bars_has_time_gaps = false
    start_of_trend_bar_index = 0
    for i = index+20 to index
        if i-1 < 0 or i-2 < 0
            continue

        last_bar_has_time_gap = (time[i-1] - time[i])/1000/60 > current_timeframe
        current_bar_start_the_trend = (time[i-2] - time[i-1])/1000/60 == current_timeframe
        if last_bar_has_time_gap and current_bar_start_the_trend
            last_bars_has_time_gaps := true
            start_of_trend_bar_index := i-1

    current_bar_is_positive = close[index] > open[index] and volume[index] > 10000 and close[index] - open[index] > 0.1
    current_bar_touched_9_ema = (low[index] <= ema_9[index] or (low[index]-ema_9[index]) < (low[index+1]-ema_9[index+1])) and (close[index] - open[index]) > (low[index] - ema_9[index])*1.5 and close[index] > ema_9[index]
    current_bar_is_strong = (close[index] - open[index]) / (high[index] - close[index] + open[index] - low[index]) >= 0.6
    current_bar_changed_direction = open[index+1] < close[index] and not (low[index] < low[index+1] and math.abs(low[index+1]-ema_9[index+1]) < math.abs(low[index]-ema_9[index]))
    previous_bar_is_weak = not (volume[index+1] > volume[index+2] and volume[index+1] > volume[index] and close[index+1] < open[index+1] and close[index+2] < open[index+2] and volume[index+1] > vol_avg[index+1])

    highest_high_index = 0
    highest_high_value = 0.0
    for i = start_of_trend_bar_index to index+2
        if i-1 < 0
            continue

        if high[i] > highest_high_value and high[i] > high[i+1] and high[i] > high[i-1] and volume[i] >= vol_avg[i] and math.abs(close[i] - open[i]) / (high[i] - low[i]) >= 0.2
            highest_high_value := high[i]
            highest_high_index := i

    highest_bar_has_huge_rejection = false
    if highest_high_index-1 > 0
        highest_bar_has_huge_rejection := close[highest_high_index] > open[highest_high_index] and (high[highest_high_index-1] - low[highest_high_index-1])/(high[highest_high_index] - low[highest_high_index]) >= 0.7

    highest_bar_is_negative_with_high_volume =
     close[highest_high_index] < open[highest_high_index]
     and close[highest_high_index+1] > open[highest_high_index+1]
     and volume[highest_high_index] > volume[highest_high_index+1]
     and (high[highest_high_index]-low[highest_high_index])/(high[highest_high_index+1]-low[highest_high_index+1]) >= 0.5
     and (high[highest_high_index] - low[highest_high_index])/(high[highest_high_index+1] - low[highest_high_index+1]) >= 0.6

    price_is_above_9_ema_until_now = true
    for i = highest_high_index-1 to index+1
        if i < 0
            continue
        if close[i] < ema_9[i] or open[i] < ema_9[i]
            price_is_above_9_ema_until_now := false
            break

    highest_price_in_last_bars = 0.0
    for i = start_of_trend_bar_index to index
        if close[i] > highest_price_in_last_bars
            highest_price_in_last_bars := close[i]

    lowest_price_in_last_bars = highest_price_in_last_bars
    for i = start_of_trend_bar_index to index
        if low[i] < lowest_price_in_last_bars
            lowest_price_in_last_bars := low[i]

    current_bar_continues_up_trend = (highest_price_in_last_bars-lowest_price_in_last_bars) / close[index] >= 0.15

    highest_volume_bar = 0.0
    for i = start_of_trend_bar_index to index
        if volume[i] > highest_volume_bar
            highest_volume_bar := volume[i]

    last_biggest_bar_is_not_weak = true
    for i = start_of_trend_bar_index to index
        if volume[i] == highest_volume_bar and close[i] < open[i]
            last_biggest_bar_is_not_weak := false
            break

    current_bar_close_is_lower_than_highest_high = close[index] < highest_high_value

    at_least_one_red_bar_between_highest_to_current_bar = false
    last_red_bar_index = 0
    last_red_bar_volume = 0.0
    for i = index+1 to highest_high_index
        if close[i] < open[i]
            at_least_one_red_bar_between_highest_to_current_bar := true
            last_red_bar_index := i
            last_red_bar_volume := volume[i]
            break

    direction_has_changed_to_upward = current_bar_is_positive
     and current_bar_touched_9_ema
     and current_bar_is_strong
     and current_bar_changed_direction
     and current_bar_close_is_lower_than_highest_high
     and not highest_bar_has_huge_rejection
     and price_is_above_9_ema_until_now
     and not highest_bar_is_negative_with_high_volume
     and current_bar_continues_up_trend
     and previous_bar_is_weak
     and last_biggest_bar_is_not_weak
     and str.tonumber(timeframe.period) >= 5
     and volume[index] > vol_avg[index]
     and open[index] > open[highest_high_index]
     and highest_high_index - index <= 7
     and start_of_trend_bar_index - index <= 7
     and at_least_one_red_bar_between_highest_to_current_bar
     and close[index] > vwap[index]
     and open[index] > low[index+1]
     and high[last_red_bar_index] < high[index]
     and last_red_bar_volume < volume[index]
     and last_bars_has_time_gaps

    // if direction_has_changed_to_upward and hour >= 4 and hour < 15
    //     log.info("Direction has changed. highest_high_index: {0}", highest_high_index)

    direction_has_changed_to_upward

direction_has_changed_to_upward = direction_has_changed_to_upward()
plotshape(hour >= 4 and hour < 15 ? direction_has_changed_to_upward : false, title="Change Direction up", color=color.green, display = display.pane, style = shape.arrowup, size = size.small, location = location.abovebar, text = change_direction_up_indication_sign)

alertcondition(ema_support_indication or direction_has_changed_to_upward or breaks_last_high_indication, title="Positive indication for long/short momentum", message="Positive indication for long/short momentum")
