import common


def get_tagged_data() -> list[common.objects.SymbolTest]:
    return [
        common.objects.SymbolTest(
            name="HBIO",
            datetime_str="10.30.25T09:52:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="EPSM",
            datetime_str="11.20.25T11:06:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="CYCU",
            datetime_str="11.14.25T12:42:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="FLYE",
            datetime_str="12.01.25T10:52:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="QCLS",
            datetime_str="12.04.25T09:43:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="TWG",
            datetime_str="12.08.25T13:10:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="AFJK",
            datetime_str="12.09.25T14:14:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="JXG",
            datetime_str="12.09.25T15:45:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="BBGI",
            datetime_str="12.10.25T09:45:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ARTV",
            datetime_str="12.15.25T13:22:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="VMAR",
            datetime_str="12.16.25T10:17:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="VMAR",
            datetime_str="12.16.25T11:28:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ASPC",
            datetime_str="12.26.25T12:25:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="INBS",
            datetime_str="01.05.26T10:00:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="JCSE",
            datetime_str="01.05.26T11:43:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="INBS",
            datetime_str="01.05.26T12:29:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="VLN",
            datetime_str="01.09.26T12:30:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="LVLU",
            datetime_str="01.12.26T11:23:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="EVTV",
            datetime_str="01.13.26T12:49:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="BNAI",
            datetime_str="01.14.26T09:51:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="AHMA",
            datetime_str="01.15.26T10:31:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="CJMB",
            datetime_str="01.15.26T11:26:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="MLEC",
            datetime_str="01.15.26T11:59:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="PRFX",
            datetime_str="01.16.26T10:45:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="POLA",
            datetime_str="01.20.26T10:02:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="NAMM",
            datetime_str="01.22.26T10:30:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ASTI",
            datetime_str="01.22.26T10:48:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BGL",
            datetime_str="01.22.26T11:42:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="BGL",
            datetime_str="01.22.26T14:24:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="QCLS",
            datetime_str="01.23.26T11:55:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AUST",
            datetime_str="01.23.26T12:45:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BNAI",
            datetime_str="01.23.26T10:24:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="MBAI",
            datetime_str="01.26.26T10:22:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="MBAI",
            datetime_str="01.26.26T11:41:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="DRMA",
            datetime_str="01.26.26T12:19:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="XTKG",
            datetime_str="01.26.26T14:11:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="MOVE",
            datetime_str="01.27.26T10:04:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="GITS",
            datetime_str="01.27.26T10:05:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="XHLD",
            datetime_str="01.27.26T15:36:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BNAI",
            datetime_str="01.28.26T10:42:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="NAMM",
            datetime_str="01.28.26T14:50:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="FEED",
            datetime_str="01.29.26T09:47:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="CATX",
            datetime_str="01.29.26T12:22:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="FEED",
            datetime_str="01.30.26T09:57:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ROMA",
            datetime_str="02.02.26T10:00:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="JLHL",
            datetime_str="02.02.26T10:46:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="CATX",
            datetime_str="02.02.26T10:48:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SORA",
            datetime_str="02.02.26T15:19:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ZCMD",
            datetime_str="02.04.26T11:23:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SMX",
            datetime_str="02.06.26T10:16:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="QVCGP",
            datetime_str="02.11.26T10:22:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="NCI",
            datetime_str="02.11.26T11:00:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="RIME",
            datetime_str="02.13.26T14:11:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ATOM",
            datetime_str="02.17.26T12:27:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="MLEC",
            datetime_str="02.18.26T10:09:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="CDIO",
            datetime_str="02.18.26T14:18:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="KNRX",
            datetime_str="02.19.26T09:46:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="RXT",
            datetime_str="02.19.26T15:12:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BIYA",
            datetime_str="02.20.26T10:49:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="NCI",
            datetime_str="02.23.26T14:19:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="LRMR",
            datetime_str="02.25.26T09:57:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="CDIO",
            datetime_str="02.25.26T11:46:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="RXT",
            datetime_str="02.26.26T10:55:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="AEHL",
            datetime_str="02.26.26T11:36:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="XWEL",
            datetime_str="02.27.26T09:30:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="TMDE",
            datetime_str="03.03.26T10:21:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="MOBX",
            datetime_str="03.03.26T11:19:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="EDSA",
            datetime_str="03.03.26T11:41:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BATL",
            datetime_str="03.04.26T11:27:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="TPET",
            datetime_str="03.05.26T09:45:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BATL",
            datetime_str="03.05.26T10:10:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="TMDE",
            datetime_str="03.05.26T11:16:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="TURB",
            datetime_str="03.05.26T12:07:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="AIFF",
            datetime_str="03.06.26T09:48:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="DXST",
            datetime_str="03.06.26T10:40:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="QCLS",
            datetime_str="03.06.26T10:54:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="EDSA",
            datetime_str="03.06.26T11:12:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SYNX",
            datetime_str="03.06.26T11:21:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="UGRO",
            datetime_str="03.06.26T12:30:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="TURB",
            datetime_str="03.09.26T09:46:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="EDSA",
            datetime_str="03.09.26T11:08:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ANTX",
            datetime_str="03.09.26T11:57:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="CAMP",
            datetime_str="03.09.26T13:51:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="DXST",
            datetime_str="03.10.26T10:15:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="PLYX",
            datetime_str="03.10.26T14:06:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ACXP",
            datetime_str="03.11.26T10:03:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SXTP",
            datetime_str="03.11.26T12:23:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="CDXS",
            datetime_str="03.12.26T09:30:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="EONR",
            datetime_str="03.12.26T11:12:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AGRZ",
            datetime_str="03.12.26T13:19:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ANTX",
            datetime_str="03.12.26T14:35:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SVCO",
            datetime_str="03.13.26T09:52:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AIFF",
            datetime_str="03.13.26T10:24:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="PLYX",
            datetime_str="03.13.26T14:21:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="LWLG",
            datetime_str="03.13.26T15:03:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="PRSO",
            datetime_str="03.16.26T14:49:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BIAF",
            datetime_str="03.17.26T09:35:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="EDSA",
            datetime_str="03.17.26T10:43:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="QCLS",
            datetime_str="03.18.26T11:30:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ACXP",
            datetime_str="03.19.26T10:12:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="GOAI",
            datetime_str="03.19.26T11:30:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="LIDR",
            datetime_str="03.19.26T12:05:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SER",
            datetime_str="03.19.26T12:38:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SER",
            datetime_str="03.20.26T09:30:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="EDSA",
            datetime_str="03.20.26T09:43:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ANNA",
            datetime_str="03.20.26T10:02:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SUNE",
            datetime_str="03.20.26T13:59:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SER",
            datetime_str="03.23.26T09:34:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SATL",
            datetime_str="03.23.26T10:07:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BIAF",
            datetime_str="03.23.26T10:42:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ANNA",
            datetime_str="03.24.26T09:37:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="UGRO",
            datetime_str="03.25.26T10:41:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SER",
            datetime_str="03.25.26T10:41:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="NXTT",
            datetime_str="03.25.26T15:04:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="NAVN",
            datetime_str="03.26.26T09:50:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="EEIQ",
            datetime_str="03.26.26T09:59:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="AIFF",
            datetime_str="03.26.26T11:42:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="NXTT",
            datetime_str="03.27.26T10:13:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ARTL",
            datetime_str="03.27.26T12:22:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SST",
            datetime_str="03.27.26T12:42:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ASTC",
            datetime_str="03.30.26T10:17:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="UGRO",
            datetime_str="03.30.26T11:48:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ANNA",
            datetime_str="03.30.26T15:56:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="KIDZ",
            datetime_str="03.31.26T09:31:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="MASK",
            datetime_str="03.31.26T09:54:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ANNA",
            datetime_str="03.31.26T12:14:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ELAB",
            datetime_str="03.31.26T15:06:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="CYCN",
            datetime_str="04.01.26T09:40:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ELAB",
            datetime_str="04.01.26T10:33:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AGPU",
            datetime_str="04.01.26T11:17:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SST",
            datetime_str="04.01.26T11:17:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SST",
            datetime_str="04.01.26T13:50:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ELAB",
            datetime_str="04.01.26T14:53:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SWMR",
            datetime_str="04.02.26T10:22:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SIDU",
            datetime_str="04.02.26T11:57:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="FUBO",
            datetime_str="04.06.26T10:03:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SMX",
            datetime_str="04.06.26T10:09:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SIDU",
            datetime_str="04.06.26T10:59:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="FUBO",
            datetime_str="04.06.26T11:50:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SKYQ",
            datetime_str="04.06.26T13:43:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AIXI",
            datetime_str="04.06.26T14:52:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SKYQ",
            datetime_str="04.07.26T09:51:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AGPU",
            datetime_str="04.07.26T10:15:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="TMDE",
            datetime_str="04.07.26T10:16:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AIXI",
            datetime_str="04.07.26T10:42:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AIXI",
            datetime_str="04.07.26T10:51:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AIXI",
            datetime_str="04.07.26T10:56:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="AIXI",
            datetime_str="04.07.26T12:29:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BMEA",
            datetime_str="04.07.26T14:20:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="MAXN",
            datetime_str="04.07.26T14:29:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="BMEA",
            datetime_str="04.07.26T14:41:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="BMEA",
            datetime_str="04.07.26T15:15:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="BMEA",
            datetime_str="04.07.26T15:52:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SKYQ",
            datetime_str="04.08.26T09:39:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SKYQ",
            datetime_str="04.08.26T10:30:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="JEM",
            datetime_str="04.08.26T10:59:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SKYQ",
            datetime_str="04.08.26T13:33:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SKYQ",
            datetime_str="04.09.26T09:47:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SKYQ",
            datetime_str="04.09.26T10:24:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="SIDU",
            datetime_str="04.09.26T10:30:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ONCO",
            datetime_str="04.09.26T10:42:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ZNTL",
            datetime_str="04.09.26T10:52:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ONCO",
            datetime_str="04.09.26T10:56:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ZNTL",
            datetime_str="04.09.26T12:16:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="VSA",
            datetime_str="04.09.26T12:46:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="VTAK",
            datetime_str="04.09.26T12:50:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="BBGI",
            datetime_str="04.09.26T13:07:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BBGI",
            datetime_str="04.09.26T14:13:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ZNTL",
            datetime_str="04.10.26T09:47:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SIDU",
            datetime_str="04.10.26T10:36:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="UCAR",
            datetime_str="04.10.26T10:50:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SKYQ",
            datetime_str="04.10.26T11:29:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="RMSG",
            datetime_str="04.13.26T11:45:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="SIDU",
            datetime_str="04.13.26T13:48:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="ARAI",
            datetime_str="04.14.26T14:29:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="XNDU",
            datetime_str="04.15.26T11:11:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="BIRD",
            datetime_str="04.15.26T11:13:00",
            is_positive=True,
        ),
        common.objects.SymbolTest(
            name="MNTS",
            datetime_str="04.15.26T11:57:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="ASTI",
            datetime_str="04.15.26T14:07:00",
            is_positive=False,
        ),
        common.objects.SymbolTest(
            name="XNDU",
            datetime_str="04.16.26T12:59:00",
            is_positive=False,
        ),
    ]
